### ISSUE TITLE
Grant type `authorization_code` does not work in OpenIddict 3.0 beta 3

### ISSUE THREAD

**Issue by fizker** [openiddict/openiddict-core#1068]
Hi,

I tried to set up my server to support the auth code flow, but it seems to fail with an internal exception when trying to verify the client_id/client_secret combo. I sent the credentials with the HTTP Basic Auth header, but the same error happens when providing the credentials in the request body.

The server logs the following messages:

```
2020-08-18 13:55:52.6205|INFO|OpenIddict.Server.OpenIddictServerDispatcher|The request address matched a server endpoint: Token.  |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
2020-08-18 13:55:52.6227|INFO|OpenIddict.Server.OpenIddictServerDispatcher|The token request was successfully extracted: {
  "code": "[redacted]",
  "grant_type": "authorization_code",
  "redirect_uri": "custom-scheme://oauth-exchange",
  "client_id": "mobile-client",
  "client_secret": "[redacted]"
}.  |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
2020-08-18 13:55:52.6384|WARN|OpenIddict.Core.OpenIddictApplicationManager|An error occurred while trying to verify a client secret.
This may indicate that the hashed entry is corrupted or malformed. System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at OpenIddict.Core.OpenIddictApplicationManager`1.<ValidateClientSecretAsync>g__VerifyHashedSecret|56_0(String hash, String secret) in /_/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs:line 1426
   at OpenIddict.Core.OpenIddictApplicationManager`1.ValidateClientSecretAsync(String secret, String comparand, CancellationToken cancellationToken) in /_/src/OpenIddict.Core/Managers/OpenIddictApplicationManager.cs:line 1410 |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
2020-08-18 13:55:52.6554|WARN|OpenIddict.Core.OpenIddictApplicationManager|Client authentication failed for mobile-client.  |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
2020-08-18 13:55:52.6562|ERROR|OpenIddict.Server.OpenIddictServerDispatcher|The token request was rejected because the confidential or hybrid application 'mobile-client' didn't specify valid client credentials.  |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
2020-08-18 13:55:52.6579|INFO|OpenIddict.Server.OpenIddictServerDispatcher|The response was successfully returned as a JSON document: {
  "error": "invalid_client",
  "error_description": "The specified client credentials are invalid."
}.  |url:POST https://localhost/api/auth/token |traceid:|9d8779a6-4ec529eff93391b1. |eventid:|
```

The interesting parts for me is that it logs a successful token request first, and correctly extracts the client_id (and presumably the client_secret), and then after that logs a `System.FormatException`. It looks like it tries to unpack the auth-header twice, but the second attempt uses invalid data.

**Comment by kevinchalet** [comment]
Hi,

Can you please share the code used to create the client application?

Thanks.

**Comment by fizker** [comment]
Sure. Because I am still in the early flow-design stage, I copied the code from https://github.com/openiddict/openiddict-core/blob/dev/samples/Mvc.Server/Worker.cs#L35-L65 and modified slightly. The version I tested against was

```cs
await manager.CreateAsync(new OpenIddictApplicationDescriptor
{
	ClientId = "mobile-client",
	ClientSecret = "901564A5-E7FE-42CB-B10D-61EF6A8F3654",
	ConsentType = ConsentTypes.Explicit,
	DisplayName = "Shared Mobile Client ID",
	RedirectUris = { new Uri("custom-scheme://oauth-exchange") },
	Permissions =
	{
		Permissions.Endpoints.Authorization,
		Permissions.Endpoints.Logout,
		Permissions.Endpoints.Token,
		Permissions.GrantTypes.AuthorizationCode,
		Permissions.GrantTypes.RefreshToken,
		Permissions.Scopes.Email,
		Permissions.Scopes.Profile,
		Permissions.Scopes.Roles,
	},
});
```

**Comment by kevinchalet** [comment]
I tried to reproduce this issue locally but so far, no luck.

What's the value of the `ClientSecret` column (in the database) for this client?

**Comment by fizker** [comment]
It looks to be exactly the string that was given in the create-call. The raw data exported from Azure Data Studio to JSON is
```
[
  {
    "Id": 3,
    "ClientId": "mobile-client",
    "ClientSecret": "901564A5-E7FE-42CB-B10D-61EF6A8F3654",
    "ConcurrencyToken": "328f99cb-1570-41bc-bf9f-58b886c53aad",
    "ConsentType": "explicit",
    "DisplayName": "Shared Mobile Client ID",
    "Permissions": "[\"ept:authorization\",\"ept:logout\",\"ept:token\",\"gt:authorization_code\",\"gt:refresh_token\",\"scp:email\",\"scp:profile\",\"scp:roles\"]",
    "PostLogoutRedirectUris": null,
    "Properties": null,
    "RedirectUris": "[\"custom-scheme://oauth-exchange\"]",
    "Type": "confidential",
    "Requirements": null,
    "DisplayNames": null
  }
]
```

To be honest, I saw this issue in Beta 2 and then decided to update to beta 3 to see if the problem had been solved. So it might be a left-over problem from that version.

I can also try to extract to a separate project later tonight. My main project is proprietary, but the relevant parts should be extractable. The problem might come from the basic OpenIddict setup in Startup.cs, I suppose.

**Comment by kevinchalet** [comment]
The client secret is typically "hashed" (using PBKDF2) before being stored in the database.

When I execute your snippet locally, the entry is correctly created (i.e with a hashed secret that looks like `AQAAAAEAACcQAAAAEB5mc/ALCfnxrlNPcc5Iwo5iNdY25jyjEtLjS7tNEHexf8ioEpVkSp7iYrJvGAmONA==`).

**Comment by kevinchalet** [comment]
Do you use custom stores or a custom application manager?

**Comment by fizker** [comment]
I did mess around trying to get it to work, so there is a non-zero chance that I might have manually broken it. I have moved on to the next part of the flow for now, but I will take a second look later today. Until then, it probably does not make much sense for you to keep digging.

**Comment by kevinchalet** [comment]
Roger that. Let's keep this ticket open until you have a chance to give it another try.

**Comment by fizker** [comment]
I have poked around a bit more, and it looks like the problem was probably that I messed around trying to figure out my client implementation, plus that I got lost when trying to match the stack trace against the OpenIddict code to see when it happened and what I should do to resolve it.

Sorry for the inconvenience.
