### ISSUE TITLE
Invalid character on header when using expired OpenId token with 'es' culture

### ISSUE THREAD

**Issue by jardg** [openiddict/openiddict-core#1164]
### Describe the bug
I'm using an API controller with authentication using OpenIdDict. My site culture is spanish. If I make a request using as authorization header an expired access token I get a 500 internal error as status code instead of the 401 with the localized error_description in the header.  This happens because OpenIdDict is returning a 401 status code and inserting a Header with key WWW-Authenticate and value the error description like this
![image](https://user-images.githubusercontent.com/6726578/99150111-94e44280-2692-11eb-8bf2-144a3e75429f.png)
Because I'm using spanish culture(es-ES) the localized error_description is "el token no es válido". That "á" character being inserted on the header makes Kestrel used to host the website fail. Then it returns internal server error to my request instead of unauthorized.

### To reproduce

I reproduced the bug using OpenIdDict library included in  Orchard Core OpenId implementation. Repo streps:
 - I downloaded the [repo ](https://github.com/OrchardCMS/OrchardCore) and used last bits from dev branch. I created a new site
- Enabled OpenId.Server,OpenId.TokenValidation and OrchardCore.Contents features.
- I changed the site default culture to es-ES 
- I setup OpenId to get a valid token using password flow. I waited the token to expire.
- I called to the OrchardContents Controller using get method with the url http://localhost:5000/api/content/5. This controller uses authentication(I cheated a bit in this one because I removed the AllowAnonymous attribute in the code of the controller to test it faster) using my expired token. Then I got the error. I attach the call
![image](https://user-images.githubusercontent.com/6726578/99150370-6a938480-2694-11eb-9833-b91c4d2af9e1.png)

### Exceptions (if any)
 System.InvalidOperationException: Invalid non-ASCII or control character in header: 0x00E1
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowInvalidHeaderCharacter(Char ch)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ValidateHeaderValueCharacters(StringValues headerValues)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.SetValueFast(String key, StringValues value)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_Item(String key, StringValues value)
   at Microsoft.AspNetCore.Http.ParsingHelpers.SetHeaderUnmodified(IHeaderDictionary headers, String key, Nullable`1 values)
   at Microsoft.AspNetCore.Http.ParsingHelpers.AppendHeaderUnmodified(IHeaderDictionary headers, String key, StringValues values)
   at OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers.AttachWwwAuthenticateHeader`1.HandleAsync(TContext context)
   at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler.HandleChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.ChallengeAsync(AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.ChallengeAsync(HttpContext context, String scheme, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /Users/user/Desktop/OrchardCore-dev/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 34

### Further technical details
- ASP.NET Core version: 3.1.10
- Visual Studio 2019

**Comment by kevinchalet** [comment]
Thanks for reporting this issue.

I took a look at the OAuth 2.0 specification and only US-ASCII chars can be used in `error_description` parameters, whether they are returned in authorization/token responses or as part of the `WWW-Authenticate` response header.

Concretely, this means we'll need to restore the pre-3.0 behavior, where non-localized descriptions are returned. It's still not clear to me what the right plan is: should we introduce a new parameter containing localized descriptions? Should we remove all the localized strings? (which means errors visible to users won't be translated...)
