### ISSUE TITLE
How to add multi-tenancy?

### ISSUE THREAD

**Issue by cryo75** [openiddict/openiddict-core#1276]
I need to add multi-tenancy using Finbuckle.Multitenant. I will be using a db per tenant. I have already configured the tenancy side in the project.

But what changes do I need to make to my OpenIddict server to enable multi-tenancy (preferably with minimal changes)?

**Comment by kevinchalet** [comment]
Hey,

I'm not a Finbuckle expert but I believe they use a variation of the approach I mentioned here: https://stackoverflow.com/questions/49596938/openid-connect-identifying-tenant-during-login/49682427#49682427

To make the OpenIddict server and validation options (aka `OpenIddictServerOptions` and `OpenIddictValidationOptions`) tenant-aware, the following instructions should work: https://www.finbuckle.com/MultiTenant/Docs/Options

If you use EF Core and want a `DbContext` per tenant, https://www.finbuckle.com/MultiTenant/Docs/EFCore should put you on the right track.

Let me know if that works for you. Otherwise, I'll take a closer look.

Cheers.

**Comment by cryo75** [comment]
My `ConfigureServices` starts with:

```csharp
services.AddDbContext<ApplicationDbContext>(options =>
{
    //options.UseSqlServer(Configuration.GetConnectionString("Identity"));
    options.UseOpenIddict();
});
```

And then continues further down with...

```csharp
services.AddOpenIddict()
    .AddCore(options =>
    {
        options.UseEntityFrameworkCore().UseDbContext<ApplicationDbContext>();
        options.UseQuartz();
    })

    .AddServer(...) // Server stuff here...

    .AddValidation(...) //Validation stuff here...
```

I then changed the `ApplicationDbContext` as follows:

```csharp
public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
{
    private readonly TenantInfo tenantInfo;

    public ApplicationDbContext(DbContextOptions options, TenantInfo tenantInfo)
        : base(options)
    {
        this.tenantInfo = tenantInfo;
    }

    public ApplicationDbContext(TenantInfo tenantInfo)
    {
        this.tenantInfo = tenantInfo;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(tenantInfo.ConnectionString);
        base.OnConfiguring(optionsBuilder);
    }
}
```

Tenant info comes from the `appsettings.json`. All tenants have the same authorization, etc... the only difference between them is the db the context needs to connect to. So the above should do the trick.

The above works to a certain degree. What concerns me is that I had to comment out the line `options.UseSqlServer(..)`. 

Is this safe to comment out at this stage as the connection string is retrieved at a later stage?

**Comment by kevinchalet** [comment]
> Is this safe to comment out at this stage as the connection string is retrieved at a later stage?

Yes, configuring the DB provider from `OnConfiguring` or from the `AddDbContext()` delegate makes no difference.

> All tenants have the same authorization, etc... the only difference between them is the db the context needs to connect to.

If they have different databases, then the authorizations will be stored in different places and can't be shared between tenants. Also, sharing the same server/validation options between all your tenants may not be ideal as they will all share the same signing/encryption credentials. If you want complete isolation between all your authorization server instances, consider using separate options and different credentials.

**Comment by cryo75** [comment]
At this stage just db per tenant should suffice. But if I would need different authorization options and credentials I will follow your SO answer.

**Comment by cryo75** [comment]
Unfortunately... I'm getting the following exception...

```csharp
[ERR] Job OpenIddict.Quartz.OpenIddictQuartzJob threw a JobExecutionException: 
Parameters: refire = True, unscheduleFiringTrigger = False, unscheduleAllTriggers = False 
 Quartz.JobExecutionException: One or more errors occurred. (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.) (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.)
 ---> System.AggregateException: One or more errors occurred. (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.) (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.)
 ---> System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreTokenStore`5.<>c__DisplayClass44_0.<<PruneAsync>g__CreateTransactionAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreTokenStore`5.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreAuthorizationStore`5.<>c__DisplayClass39_0.<<PruneAsync>g__CreateTransactionAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreAuthorizationStore`5.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)<---

   --- End of inner exception stack trace ---
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken) [See nested exception: System.AggregateException: One or more errors occurred. (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.) (No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.)
 ---> System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreTokenStore`5.<>c__DisplayClass44_0.<<PruneAsync>g__CreateTransactionAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreTokenStore`5.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.InvalidOperationException: No database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.Initialize(IServiceProvider scopedProvider, IDbContextOptions contextOptions, DbContext context)
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreAuthorizationStore`5.<>c__DisplayClass39_0.<<PruneAsync>g__CreateTransactionAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenIddict.EntityFrameworkCore.OpenIddictEntityFrameworkCoreAuthorizationStore`5.PruneAsync(DateTimeOffset threshold, CancellationToken cancellationToken)
   at OpenIddict.Quartz.OpenIddictQuartzJob.Execute(IJobExecutionContext context)<---
]
```

This must be related to the above changes I did for multi-tenancy but I can't figure out why this occurs.

**Comment by kevinchalet** [comment]
Do "normal" OpenIddict operations (typically, the authentication flow) work if you temporarily disable Quartz.NET?

**Comment by cryo75** [comment]
Yes. Everything works fine.

**Comment by kevinchalet** [comment]
Can you try removing the `public ApplicationDbContext(TenantInfo tenantInfo)` constructor?
Also, try updating the other one to use a generic argument: `public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options, TenantInfo tenantInfo)`.

**Comment by cryo75** [comment]
Exception still thrown.

**Comment by kevinchalet** [comment]
I'm out of ideas. I'll need to work on a repro, this may take some time.

**Comment by cryo75** [comment]
No problem. I might remove multi-tenancy completely.

**Comment by mphill** [comment]
@cryo75 

commenting out `options.UseSqlServer(Configuration.GetConnectionString("Identity"));` is indeed the right thing to do, but causes other issues as you've noted with the DbContext essentially not having a connection string.

The problem is any operation have occurs outside of a web request won't allow have enough information to figure out how to route to the correct DbContext. This is certainly the case with a background job. 

This [issue](https://github.com/Finbuckle/Finbuckle.MultiTenant/issues/312)  offered a way to get Finbuckle to essentially manually override its internals so that Openiddict can use the correct DbContext from outside of a web request

In my case I wanted to **seed** client IDs and secrets when the app started for each tenant, this was my solution:

```csharp
    using var scope = _scopeFactory.CreateScope();

    var accessor = scope.ServiceProvider.GetRequiredService<IMultiTenantContextAccessor>();
    var multiTenantContext = new MultiTenantContext<TenantInfo>
    {
        TenantInfo = tenant
    };

    accessor.MultiTenantContext = multiTenantContext;

    var applicationManager = scope.ServiceProvider.GetRequiredService<IOpenIddictApplicationManager>(); 

    var client = await applicationManager.FindByClientIdAsync(tenant.ServiceAccountClientId); 
```


@kevinchalet Does Openiddict expose a method/service to clean expired token?  That would be easy to use with this so you could have multi-tenant token cleanup. Hope that helps.

**Comment by chihabhajji** [comment]
i guess my concern isnt really hooking up the EFCore Db contexts, but rather how to use PerTenantAuthentication properly, by either adding clientId + secret in the tenant class or something else

**Comment by chihabhajji** [comment]
i have managed to implement host based multi-tenancy and when the tenant id cant be extracted all requests are not even hit, but for some reason, i can get to https://localhost:5001/.well-known/openid-configuration and i get the discovery document back
