### ISSUE TITLE
Problems hosting openiddict application on more as one node in kubernetes

### ISSUE THREAD

**Issue by AndreGl** [openiddict/openiddict-core#1292]
### Describe the bug
In case the openiddict server is hosted on kubernetes and runs on more as one node the follow error happen.
In the application self I already configure DataProtection at Startup.
```
            services.AddDataProtection()
                .SetApplicationName(appSettings.DataProtectionKeyName)
                .PersistKeysToDbContext<ApplicationDbContext>();
```

I also tried to configure a unique jwt key, but none positive effect.
```
            var key = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(appSettings.AuthenticationTokenSecretKey))
                { KeyId = appSettings.AuthenticationTokenSecretKeyId };
            services.AddOpenIddict()

                // Register the OpenIddict core components.
                .AddCore(options =>
                {
                    // Configure OpenIddict to use the Entity Framework Core stores and models.
                    // Note: call ReplaceDefaultEntities() to replace the default OpenIddict entities.
                    options.UseEntityFrameworkCore()
                           .UseDbContext<ApplicationDbContext>();
                })

                // Register the OpenIddict server components.
                .AddServer(options =>
                {
                    // Enable the authorization, device, logout, token, userinfo and verification endpoints.
                    options.SetAuthorizationEndpointUris("/connect/authorize")
                           .SetDeviceEndpointUris("/connect/device")
                           .SetLogoutEndpointUris("/connect/logout")
                           .SetTokenEndpointUris("/connect/token")
                           .SetUserinfoEndpointUris("/connect/userinfo")
                           .SetVerificationEndpointUris("/connect/verify");


                    options.AddSigningKey(key);
                    options.AddEncryptionKey(key);
                    // options.AddEphemeralEncryptionKey(SecurityAlgorithms.Aes256KW);
                    // options.AddEphemeralSigningKey(SecurityAlgorithms.Aes256KW);

                    // https://documentation.openiddict.com/configuration/token-formats.html
                    options.UseDataProtection();

                    // Note: this sample uses the code, device code, password and refresh token flows, but you
                    // can enable the other flows if you need to support implicit or client credentials.
                    options.AllowAuthorizationCodeFlow()
                           .AllowDeviceCodeFlow()
                           .AllowPasswordFlow()
                           .AllowRefreshTokenFlow();

                    // Mark the "email", "profile", "roles" and "demo_api" scopes as supported scopes.
                    options.RegisterScopes(OpenIddictConstants.Permissions.Scopes.Email, OpenIddictConstants.Permissions.Scopes.Profile, OpenIddictConstants.Permissions.Scopes.Roles);

                    // Register the signing and encryption credentials.
                    options.AddDevelopmentEncryptionCertificate()
                           .AddDevelopmentSigningCertificate();

                    // Force client applications to use Proof Key for Code Exchange (PKCE).
                    options.RequireProofKeyForCodeExchange();

                    // Register the ASP.NET Core host and configure the ASP.NET Core-specific options.
                    options.UseAspNetCore()
                           .EnableStatusCodePagesIntegration()
                           .EnableAuthorizationEndpointPassthrough()
                           .EnableLogoutEndpointPassthrough()
                           .EnableTokenEndpointPassthrough()
                           .EnableUserinfoEndpointPassthrough()
                           .EnableVerificationEndpointPassthrough();
                })

                // Register the OpenIddict validation components.
                .AddValidation(options =>
                {
                    // Import the configuration from the local OpenIddict server instance.
                    options.UseLocalServer();

                    // Register the ASP.NET Core host.
                    options.UseAspNetCore();

                    // https://documentation.openiddict.com/configuration/token-formats.html
                    options.UseDataProtection();

                    options.AddEncryptionKey(key);
                    // For applications that need immediate access token or authorization
                    // revocation, the database entry of the received tokens and their
                    // associated authorizations can be validated for each API call.
                    // Enabling these options may have a negative impact on performance.
                    options.EnableAuthorizationEntryValidation();
                    options.EnableTokenEntryValidation();
                });
```

The problem:
Login in redirects to OpenId application, you can do the login there, on redirect back to the application which request ***/signin_oidc these error happens.

And not happens with a single Node. 
On multi nodes also the try again works, when you reach the node where you did the login. 
So it looks like the request which exchanged is signed somehow based on the machine where the application is running and the DataProtection key which is configured is not used.

### To reproduce

Its difficult to reproduce because it works well on single node
```

8.7.2021 14:59:39 fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
8.7.2021 14:59:39       Exception occurred while processing message.
8.7.2021 14:59:39 Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
8.7.2021 14:59:39 kid: 'System.String'.
8.7.2021 14:59:39 Exceptions caught:
8.7.2021 14:59:39  'System.Text.StringBuilder'.
8.7.2021 14:59:39 token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
8.7.2021 14:59:39    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
8.7.2021 14:59:39    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
8.7.2021 14:59:39 fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
8.7.2021 14:59:39       An unhandled exception has occurred while executing the request.
8.7.2021 14:59:39 System.Exception: An error was encountered while handling the remote login.
8.7.2021 14:59:39  ---> Microsoft.IdentityModel.Tokens.SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match key:
8.7.2021 14:59:39 kid: 'System.String'.
8.7.2021 14:59:39 Exceptions caught:
8.7.2021 14:59:39  'System.Text.StringBuilder'.
8.7.2021 14:59:39 token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.
8.7.2021 14:59:39    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
8.7.2021 14:59:39    at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.ValidateToken(String idToken, AuthenticationProperties properties, TokenValidationParameters validationParameters, JwtSecurityToken& jwt)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
8.7.2021 14:59:39    --- End of inner exception stack trace ---
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
8.7.2021 14:59:39    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
8.7.2021 14:59:39    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

### Exceptions (if any)
None exception in core code

### Further technical details
Application run in Dockerfile based on mcr.microsoft.com/dotnet/aspnet:5.0

**Comment by kevinchalet** [comment]
Hi,

![image](https://user-images.githubusercontent.com/6998306/99829612-cf4f5300-2b5c-11eb-843b-d6b365965c0a.png)

As indicated, the ability to post questions on GitHub is reserved to sponsors as a way to thank them. Please consider [sponsoring  the project](https://github.com/sponsors/kevinchalet) or post your question on StackOverflow, where it will be visible by the community.

> Its difficult to reproduce because it works well on single node

It's not a bug: you configured OpenIddict to use developer signing certificates so two certificates (one per node) end up being created. If you don't have session affinity, tokens produced by node A end up being validated by B, that uses different keys.

Thanks.
