### ISSUE TITLE
Token is Rejected even Though it has not Expired

### ISSUE THREAD

**Issue by Camuvingian** [openiddict/openiddict-core#1679]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

3.x (no longer supported)

### Question

I am using the following code to setup the lifetime/span of my authentication tokens 

    public static IServiceCollection AddOpenIddictServices(this IServiceCollection services, IConfigurationRoot configurationRoot)
    {
        var authOptions = GetAuthenticationOptions(configurationRoot);

        services
            .AddOpenIddict()
            .AddCore(options =>
            {
                options.UseMongoDb()
                       .UseDatabase(new MongoClient(_mongoDbSettings.ConnectionString).GetDatabase(_mongoDbSettings.DatabaseName))
                       .SetApplicationsCollectionName("applications")
                       .SetAuthorizationsCollectionName("authorizations")
                       .SetTokensCollectionName("tokens")
                       .SetScopesCollectionName("scopes");

                options.UseQuartz();
            })
            .AddServer(options =>
            {
                options
                    .SetAuthorizationEndpointUris("/api/authorization/authorize")
                    .SetTokenEndpointUris("/api/authorization/token");

                options
                    .AllowAuthorizationCodeFlow()
                    .AllowPasswordFlow()
                    .AllowRefreshTokenFlow();

                options.AcceptAnonymousClients();
                options.RegisterScopes(Scopes.Email, Scopes.Profile, Scopes.Roles, CustomScopes.DefaultAccess, CustomScopes.OfflineAccess);

                // Register the development signing and encryption credentials.
                options
                    .AddDevelopmentEncryptionCertificate()
                    .AddDevelopmentSigningCertificate();

                options
                    .SetAccessTokenLifetime(TimeSpan.FromSeconds(authOptions.AccessTokenLifetimeSeconds))
                    .SetRefreshTokenLifetime(TimeSpan.FromSeconds(authOptions.RefreshTokenLifetimeSeconds))
                    .SetRefreshTokenReuseLeeway(TimeSpan.FromSeconds(authOptions.RefreshTokenReuseLeewaySeconds));

                // Force client applications to use Proof Key for Code Exchange (PKCE).
                //options.RequireProofKeyForCodeExchange();

                // Register the ASP.NET Core host and configure the ASP.NET Core-specific options.
                options
                    .UseAspNetCore()
                    .EnableStatusCodePagesIntegration()
                    .EnableAuthorizationEndpointPassthrough()
                    .EnableTokenEndpointPassthrough()
                    // TODO During development, you can disable the HTTPS requirement.
                    .DisableTransportSecurityRequirement();
            })
            .AddValidation(options =>
            {
                // Configure the audience accepted by this resource server.
                // The value MUST match the audience associated with the
                // "demo_api" scope, which is used by ResourceController.
                //options.AddAudiences("resource_server");

                // Import the configuration from the local OpenIddict server instance.
                options.UseLocalServer();

                // Register the ASP.NET Core host.
                options.UseAspNetCore();

                // For applications that need immediate access token or authorization
                // revocation, the database entry of the received tokens and their
                // associated authorizations can be validated for each API call.
                // Enabling these options may have a negative impact on performance.
                //
                // options.EnableAuthorizationEntryValidation();
                // options.EnableTokenEntryValidation();
            });
        return services;
    }
    
This seems to work fine and I am setting all of the three lifetime options as follows

    "AccessTokenLifetimeSeconds": 86400,
    "RefreshTokenLifetimeSeconds": 86400,
    "RefreshTokenReuseLeewaySeconds": 86400,
    
However, despite my tokens having "Token expiry date time = Fri Feb 17 2023 14:09:43 GMT+0000 (Greenwich Mean Time)" right now (Fri Feb 17 2023 13:10:XX GMT+0000 Greenwich Mean Time), requests to one of my aspnetcore controllers is failing auth. The controller is 

    [HttpGet("userdetails")]
    [IgnoreAntiforgeryToken]
    [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]
    [ProducesResponseType(StatusCodes.Status200OK, Type = typeof(UserDetailsResponseDto))]
    [ProducesResponseType(StatusCodes.Status401Unauthorized, Type = typeof(UserDetailsResponseDto))]
    [ProducesResponseType(StatusCodes.Status404NotFound, Type = typeof(UserDetailsResponseDto))]
    public async Task<IActionResult> GetUserDetails()
    {
        var user = await _userManager.GetUserAsync(User);
        if (user is null)
        {
            string message = "The specified access token is bound to an account that no longer exists";
            _logger?.LogInformation(message);

            return Challenge(
                authenticationSchemes: OpenIddictServerAspNetCoreDefaults.AuthenticationScheme,
                properties: new AuthenticationProperties(new Dictionary<string, string>
                {
                    [OpenIddictServerAspNetCoreConstants.Properties.Error] = Errors.InvalidToken,
                    [OpenIddictServerAspNetCoreConstants.Properties.ErrorDescription] = message
                }));
        }

        var responseDto = new UserDetailsResponseDto
        {
            UserName = user.UserName, 
            Roles = user.Roles,
            Errors = new List<ErrorDto>()
        };

        // Get secure details. 
        var organizationReadModel = await _organizationMongoRepository.GetOrganizationAsync(user.OrganizationId);
        if (organizationReadModel is null)
        {
            string errorMessage = $"Could not locate a linked organization for user {user.UserName}";

            responseDto.Succeeded = false;
            responseDto.Errors.Add(new ErrorDto
            {
                Code = StatusCodes.Status404NotFound.ToString(),
                Description = errorMessage
            });

            _logger?.LogError(errorMessage);

            return NotFound(responseDto);
        }

        var organizationDetails = _mapper.Map<OrganizationDetailsDto>(organizationReadModel);
        responseDto.OrganizationDetails = organizationDetails;
        responseDto.Succeeded = true;

        _logger?.LogInformation(
            "Successfully retrieved user details for {UserName} - organization {Organization}",
            user.UserName,
            organizationDetails.OrganizationName);

        return Ok(responseDto);
    }
    
The request is done as follows 

    using var request = new HttpRequestMessage(
        HttpMethod.Get,
        $"{AddressHelper.AuthenticationServerUrlBase}{AddressHelper.AuthenticationServerPort}/api/resource/userdetails");
    request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);

    using var response = await _httpClient.SendAsync(request);
    
This is failing with the following message 

    [13:06:07.754 INF] [] [Microsoft.AspNetCore.Hosting.Diagnostics] Request starting HTTP/1.1 GET https://localhost:6699/api/resource/userdetails - -
    [13:06:07.758 INF] [] [OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler] "OpenIddict.Validation.AspNetCore" was not authenticated. Failure message: "An error occurred while authenticating the current request."
    [13:06:07.758 INF] [] [Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed. "These requirements were not met:\r\nDenyAnonymousAuthorizationRequirement: Requires an authenticated user."
    [13:06:07.759 INF] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The response was successfully returned as a challenge response: "{\r\n  \"error\": \"invalid_token\",\r\n  \"error_description\": \"The specified token is invalid.\",\r\n  \"error_uri\": \"https://documentation.openiddict.com/errors/ID2004\"\r\n}".
    [13:06:07.759 INF] [] [OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler] AuthenticationScheme: "OpenIddict.Validation.AspNetCore" was challenged.
    [13:06:07.760 INF] [] [Microsoft.AspNetCore.Hosting.Diagnostics] Request finished HTTP/1.1 GET https://localhost:6699/api/resource/userdetails - - - 401 0 - 5.4159ms
    
and my code is not even being entered. The obvious answer is that the token has expired, but I am sure this is not the case here as I am setting the expiry as above and I verify when the token was created and the expiry date time has not past. I have been debugging this for several hours already... 

Is there any chance you can advise how to work out what is going wrong here?

**Comment by kevinchalet** [comment]
Hey,

> Is there any chance you can advise how to work out what is going wrong here?

Please change the ASP.NET Core log level to `Trace` to have more complete logs and post them once you have collected them 😃

**Comment by Camuvingian** [comment]
Thank you very much for your quick response @kevinchalet. Here is the details log dump... 

```
[14:34:06.345 DBG] [] [Microsoft.AspNetCore.Server.Kestrel.Connections] Connection id ""0HMOGUG31ILN0"" accepted.
[14:34:06.346 DBG] [] [Microsoft.AspNetCore.Server.Kestrel.Connections] Connection id ""0HMOGUG31ILN0"" started.
[14:34:06.365 DBG] [] [Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware] Connection "0HMOGUG31ILN0" established using the following protocol: Tls12
[14:34:06.399 INF] [] [Microsoft.AspNetCore.Hosting.Diagnostics] Request starting HTTP/1.1 GET https://localhost:6699/api/resource/userdetails - -
[14:34:06.421 DBG] [] [Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware] Wildcard detected, all requests with hosts will be allowed.
[14:34:06.421 VRB] [] [Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware] All hosts are allowed.
[14:34:06.446 DBG] [] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] 1 candidate(s) found for the request path '"/api/resource/userdetails"'
[14:34:06.448 DBG] [] [Microsoft.AspNetCore.Routing.Matching.DfaMatcher] Endpoint '"Migr8.AuthenticationServer.Controllers.ResourceController.GetUserDetails (Migr8.AuthenticationServer)"' with route pattern '"api/Resource/userdetails"' is valid for the request path '"/api/resource/userdetails"'
[14:34:06.449 DBG] [] [Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware] Request matched endpoint '"Migr8.AuthenticationServer.Controllers.ResourceController.GetUserDetails (Migr8.AuthenticationServer)"'
[14:34:06.462 DBG] [] [Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware] Static files was skipped as the request already matched an endpoint.
[14:34:06.528 DBG] [] [OpenIddict.Server.OpenIddictServerDispatcher] The event "OpenIddict.Server.OpenIddictServerEvents+ProcessRequestContext" was successfully processed by "OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandlers+InferEndpointType".
[14:34:06.530 DBG] [] [OpenIddict.Server.OpenIddictServerDispatcher] The event "OpenIddict.Server.OpenIddictServerEvents+ProcessRequestContext" was successfully processed by "OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandlers+InferIssuerFromHost".
[14:34:06.563 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessRequestContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+InferIssuerFromHost".
[14:34:06.568 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+ExtractAccessTokenFromAuthorizationHeader".
[14:34:06.569 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+ExtractAccessTokenFromBodyForm".
[14:34:06.570 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+ExtractAccessTokenFromQueryString".
[14:34:06.570 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was successfully processed by "OpenIddict.Validation.OpenIddictValidationHandlers+ValidateToken".
[14:34:06.625 VRB] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] An error occurred while validating the token '"eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZDQkMtSFM1MTIiLCJraWQiOiIzOEUwRjkzRUNFMTA2MTk4NkRERTIyMURDNUZEQjk3QTYxN0YyQjdGIiwidHlwIjoiYXQrand0In0.OSteVoAcLOnqdkwy1H8T0CEKAv21Fzp2yxifnzS77OyfKoFe6phrFiamHSk63o9yDQKtrqbwitbfnK-tAZoNlfi_70-n31pNxv26GBSZIL_JLJAAaz8mFIGdfLGxf2KgoCWgxBJg6Un2_ArnAw5Uxmpn0XaO7pbr4QGS55Ju1D_gKZbQB88-Ps0UiPEvPtg9lMfINjS2d0gwHk8jxLhfur0OVsJykrmrmaJg7Lanphs4EgNngk5t-wfwlsQWdXEWrdbh-D9Nbqm2SgTyg5OGf0-Bu2USWvsYLmfmve-RiS9bJ_T6SgZQXwrz2BmxG0WfqkNQrKs7NBYh7LdLTMJU4Q.gdcYsra_CC8tmfS9Sbvs_g.jRzwSvHw9lFf8S13QrSi4OaL2XGD0cITEPJbOxySx9VL4skove_lBcwymbYkkTs0wyMPdG1hSde9NDFmNGjjY1gsYU83NgDCako-r3C2ZRGWGAnjBRcVm9GpQFVWm5xny-j9PA_mSQLHu-o2stabZSXPkFU3WTVPQk6kExrqW7DRT-1pSgrmC5DQ84-Ay9D8Q5j6TWe9HKQ2_JigPVUJfVlHwEvyQrSqmumDRdN3dWcNLiI9njPJBQjtZkjO82x0DGlgW18QZJ1P6ihBmXsyJ11Xg8DHD-8YZdtD6OclQsXmW5VIG41099qqTT9HoepZ3nW46ZzumpWIPbnOz8xFUOjzao3rpa9H3yEqa30Vr0Ot3ex3x9r7xkzPkas2OwgUy7wpvW1tzcnI4Utom_tQOVUK38GTXhhWxPJBaP6tU9d6fDX4shiBCdhAICbGEb3XLu-O77O11jQ4BP4laje0Jsm3J9Lrs0xu-9wHYZMbmsMLjaiVHDOOj6xesH8FEegCBp9vq_y6asfWhpvSGiyz9BHaQgKIiPCVOZqsJISd9xX4ILKFEu0drpjNi_gYbZID72m1YCM7pW4RkeIiQKNQV4pEFh-KQhf6cvC0GpTtOE-17xhXtvO1nIClFPhLOEyJ8IlunhDSHbaWwPOkjEeZlGbdZCJLh61_TFsyc3qyOWfIaCGuglbJ1qLZ4svLasNQyUNP5ebtoHn1Soe07NKm0c9qDmOCHBXFuRvnadmaN5CyRwrmbt7bx01FJHwcmkVlNdcQFUc5p4apZlL0Jze_fbUiUbQ3HDacJNrTPqLsmq0--E8b6cLMyCsFcJXCjUBLqXLEZcmXzXs6fbPGYdC8XXeLsKclm7WZxNE3K0MzOL2fLFbVuKZyFNKpnN1bA0MdG5Gg3FUNrrumsraei00zJoZQJZsfLsl1LduSW9AkbTOOeWUvCiymH5-PTzEIIhyF8A9OF5w8uzRHV01X6NdNJWECPciVwQCGwtcVlKzP-w3mlb8L6jvRJjVAy68izT8L5b22O5Z8z3BLTEcHxCNLt0cr5g4l0eC6EloAZ0VdCLrfxGgDTEK-IGTe7JGLsR-IBdLSkfcsHtt7HzMlcIowSjg6x5TktvrCgQQ-HTIN9tWXdhIxfgQOBfRX7yAjQOwvPLrKN6bn5nkC0s_0XbvAqbq97gZT3pzPwyDRHAzljCKKsAwtMyAmZy-56NbsoOK3wjpPtZ-BAtJnBapSHhyHbg.Eynikdf8ZzIjsTnp6HLXUK_sohDirtdh0DG5qeF1mEU"'.
Microsoft.IdentityModel.Tokens.SecurityTokenKeyWrapException: IDX10618: Key unwrap failed using decryption Keys: 'System.Text.StringBuilder'.
Exceptions caught:
 'System.Text.StringBuilder'.
token: 'Microsoft.IdentityModel.JsonWebTokens.JsonWebToken'.
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.GetContentEncryptionKeys(JsonWebToken jwtToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.DecryptToken(JsonWebToken jwtToken, TokenValidationParameters validationParameters)
   at Microsoft.IdentityModel.JsonWebTokens.JsonWebTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters)
[14:34:06.628 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was successfully processed by "OpenIddict.Validation.OpenIddictValidationHandlers+ValidateIdentityModelToken".
[14:34:06.629 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessAuthenticationContext" was marked as rejected by "OpenIddict.Validation.OpenIddictValidationHandlers+ValidateIdentityModelToken".
[14:34:06.630 INF] [] [OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler] "OpenIddict.Validation.AspNetCore" was not authenticated. Failure message: "An error occurred while authenticating the current request."
[14:34:06.633 INF] [] [Microsoft.AspNetCore.Authorization.DefaultAuthorizationService] Authorization failed. "These requirements were not met:\r\nDenyAnonymousAuthorizationRequirement: Requires an authenticated user."
[14:34:06.638 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+AttachHostChallengeError".
[14:34:06.640 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.OpenIddictValidationHandlers+AttachDefaultChallengeError".
[14:34:06.641 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+AttachHttpResponseCode`1[[OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext, OpenIddict.Validation, Version=3.1.1.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]]".
[14:34:06.641 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+AttachCacheControlHeader`1[[OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext, OpenIddict.Validation, Version=3.1.1.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]]".
[14:34:06.643 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+AttachWwwAuthenticateHeader`1[[OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext, OpenIddict.Validation, Version=3.1.1.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]]".
[14:34:06.646 INF] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The response was successfully returned as a challenge response: "{\r\n  \"error\": \"invalid_token\",\r\n  \"error_description\": \"The specified token is invalid.\",\r\n  \"error_uri\": \"https://documentation.openiddict.com/errors/ID2004\"\r\n}".
[14:34:06.646 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was successfully processed by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+ProcessChallengeErrorResponse`1[[OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext, OpenIddict.Validation, Version=3.1.1.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]]".
[14:34:06.646 DBG] [] [OpenIddict.Validation.OpenIddictValidationDispatcher] The event "OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext" was marked as handled by "OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandlers+ProcessChallengeErrorResponse`1[[OpenIddict.Validation.OpenIddictValidationEvents+ProcessChallengeContext, OpenIddict.Validation, Version=3.1.1.0, Culture=neutral, PublicKeyToken=35a561290d20de2f]]".
[14:34:06.647 INF] [] [OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler] AuthenticationScheme: "OpenIddict.Validation.AspNetCore" was challenged.
[14:34:06.657 DBG] [] [Microsoft.AspNetCore.Server.Kestrel.Connections] Connection id ""0HMOGUG31ILN0"" completed keep alive response.
[14:34:06.659 INF] [] [Microsoft.AspNetCore.Hosting.Diagnostics] Request finished HTTP/1.1 GET https://localhost:6699/api/resource/userdetails - - - 401 0 - 261.1672ms
```

**Comment by Camuvingian** [comment]
Annoyingly, this issue happens only after some indeterminate amount of time, and I had to pop out, the token is actually now expired, but I ran the request with it anyway and got the same response. This indicates that the token was expired, or at least deemed expired 4-5 hours ago when this first started happening. I will await your expertise...

**Comment by kevinchalet** [comment]
> Thank you very much for your quick response @kevinchalet.

Thanks for sponsoring the project 😃 

> This indicates that the token was expired, or at least deemed expired 4-5 hours ago when this first started happening. I will await your expertise...

The logs seem to indicate a different root cause, that has nothing to do with expiration: IdentityModel - the Microsoft library used to generate and validate JWT tokens - is unable to decrypt the token you sent.

How do you store your signing and encryption keys/certificates? Is your app hosted on multiple instances/servers?

**Comment by Camuvingian** [comment]
So this issue is coming from a NextJS TypeScript application running on Azure in a Docker container - the client and server for the app are running in the same container. The HTTPS certs are stored in the container and are managed by Azure. They are stored in /var/ssl/certs.  I hope this is what you mean...

**Comment by Camuvingian** [comment]
When the user logs in to the site, the auth token that is returned is stored in a session cookie, perhaps somehow this is becoming corrupted, I will see if I can verify this, but ensuring I log out the initial working token - I guess I can then inspect the token again when this issue start occuring again for the same session. Perhaps this might tell me how this is happening.

**Comment by kevinchalet** [comment]
> The HTTPS certs are stored in the container and are managed by Azure. They are stored in /var/ssl/certs. I hope this is what you mean...

I actually meant the crypto material that is used to protect the tokens issued by OpenIddict (which is generally referred to as a signing/encryption key and can be embedded in a standard X.509 certificate). This is unrelated to TLS/HTTPS and strictly used for tokens protection.

In the snippet you shared, you have this:

```csharp
// Register the development signing and encryption credentials.
            options
                .AddDevelopmentEncryptionCertificate()
                .AddDevelopmentSigningCertificate();
```

But as the name and the code comment imply, these convenient methods are reserved to dev scenarios (they are not expected to work for deployed apps), so it's likely you have more traditional `.AddEncryption(Key/Certificate)` calls in your real app. So back to my question: how do you store these keys/certificates?

**Comment by Camuvingian** [comment]
We only have DEV environments running right now, so this is the code as-is. The setup/configuration above is what is currently operational.

**Comment by Camuvingian** [comment]
I would be more than happy to add you to the repo if this would help.

**Comment by kevinchalet** [comment]
This is likely the root cause of your issue: these extensions are for local development-only. For deployed apps, you need to use different options. https://documentation.openiddict.com/configuration/encryption-and-signing-credentials.html should put you on the right track.

**Comment by Camuvingian** [comment]
Okay, excellent, thank you. I will take a look now. Again, thank you very much for your time here.

**Comment by Camuvingian** [comment]
One thing however, is it not odd that the tokens work, but then stop working after some random period of time? If this was the issue, would you not expect this to be an issue as soon as the token is issued?

**Comment by kevinchalet** [comment]
> One thing however, is it not odd that the tokens work, but then stop working after some random period of time? If this was the issue, would you not expect this to be an issue as soon as the token is issued?

These extensions store the certificates using the BCL `X509Store` API: since your application executes inside a Docker container, it's very likely you don't have anything to persist and re-install the dev' certificates when the container stops/starts: when the app restarts, the previous certificates are lost and IdentityModel can't decrypt the tokens that were generated with the old crypto material.

**Comment by Camuvingian** [comment]
Hi Kevin, I used the following code to generate some enc/sgn certificates for use with my service...

```
using var algorithm = RSA.Create(keySizeInBits: 2048);

var subject = new X500DistinguishedName("CN=Fabrikam Encryption Certificate");
var request = new CertificateRequest(subject, algorithm, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
request.CertificateExtensions.Add(new X509KeyUsageExtension(X509KeyUsageFlags.KeyEncipherment, critical: true));

var certificate = request.CreateSelfSigned(DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddYears(2));

File.WriteAllBytes("encryption-certificate.pfx", certificate.Export(X509ContentType.Pfx, string.Empty));
```
I think hook this up as follows 
```
options
	.AddEncryptionCertificate(GetX509Certificate(
		Constants.Migr8TokenEncPfxFileName, 
		_authenticationOptions.Migr8TokenEncPfxPassword))
	.AddSigningCertificate(GetX509Certificate(
		Constants.Migr8TokenSgnPfxFileName, 
		_authenticationOptions.Migr8TokenSgnPfxPassword));
```
where I am injecting the passwords for these from ENV vars and the .pfx files themselves are read from a secure location in the container. But I am getting the following FTL error...

> [16:43:58.968 FTL] [] [] System.InvalidOperationException: The specified certificate is not a signing certificate.
>    at Microsoft.Extensions.DependencyInjection.OpenIddictServerBuilder.AddSigningCertificate(X509Certificate2 certificate)
>    at Migr8.AuthenticationServer.Configuration.ServiceCollectionBuilder.<>c__DisplayClass10_0.<AddOpenIddictServices>b__1(OpenIddictServerBuilder options) in C:\VRPM\Repos\authentication-server\src\Services\Migr8.AuthenticationServer\Configuration\ServiceCollectionBuilder.cs:line 187
>    at Microsoft.Extensions.DependencyInjection.OpenIddictServerExtensions.AddServer(OpenIddictBuilder builder, Action`1 configuration)
>    at Migr8.AuthenticationServer.Configuration.ServiceCollectionBuilder.AddOpenIddictServices(IServiceCollection services, IConfigurationRoot configurationRoot) in C:\VRPM\Repos\authentication-server\src\Services\Migr8.AuthenticationServer\Configuration\ServiceCollectionBuilder.cs:line 160
>    at Migr8.AuthenticationServer.Startup.ConfigureServices(IServiceCollection services) in C:\VRPM\Repos\authentication-server\src\Services\Migr8.AuthenticationServer\Startup.cs:line 65
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
>    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass14_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
>    at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
>    at Microsoft.Extensions.Hosting.HostBuilder.Build()
>    at Migr8.AuthenticationServer.Program.Main(String[] args) in C:\VRPM\Repos\authentication-server\src\Services\Migr8.AuthenticationServer\Program.cs:line 17
> [16:43:59.265 FTL] [] [] FATAL ERROR OCCURRED, authentication-server must shutdown, press any key to close

Any ideas on why these are not working, I am following the suggestions on PFX generation from the link you provided above.

**Comment by kevinchalet** [comment]
> Any ideas on why these are not working, I am following the suggestions on PFX generation from the link you provided above.

The documentation has 2 (slightly different) snippets - one for the signing certificate and one for the encryption certificate. You likely tried to use the same one for both certificates.

**Comment by Camuvingian** [comment]
I am a baffoon.

**Comment by kevinchalet** [comment]
lol 🤣

**Comment by kevinchalet** [comment]
@Camuvingian did you have a chance to confirm your issue was solved after using persistent keys/certificates?

**Comment by Camuvingian** [comment]
Sorry, I have just seen this. Yes, I believe this has resolved the issue. Thanks again for your help.
