### ISSUE TITLE
After deployment to IIS Server: A signing key must be provided

### ISSUE THREAD

**Issue by snowping** [openiddict/openiddict-core#169]
Dear community,

Since a newer version of openiddict I am having an issue with deployment to my IIS host. It seems that the access token cannot be signed anymore. I got the following error: `A signing key must be provided`

I also tried to install a self cert 509 certificate using the plural sight cert tool and installed it added it to the startup config using `AddSigningCertificate()` (see below): 

```
            // Register the OpenIddict services, including the default Entity Framework stores.
            services.AddOpenIddict<ApplicationUser, ApplicationRole, ApplicationDbContext>()
                .AddTokenManager<CustomOpenIddictTokenManager>()
                .AddUserManager<CustomOpenIddictUserManager>()
                .EnableTokenEndpoint("/connect/token")
                .AllowPasswordFlow()
                .AllowRefreshTokenFlow()
                .AddSigningCertificate("64CDD1397EF7E90869E4F50741EF55FDBE583781", StoreName.My, StoreLocation.LocalMachine) //Self-Signed-Cert using https://www.pluralsight.com/blog/software-development/selfcert-create-a-self-signed-certificate-interactively-gui-or-programmatically-in-net
                // During development, you can disable the HTTPS requirement.
                //.DisableHttpsRequirement()
                .UseJsonWebTokens();
```

Using my own 509 certificate I got the error: 
`opencsp failed with error code 2148073494`

Any help/hints appreciated. Thanks, Joël

**Comment by kevinchalet** [comment]
Hey,

The `A signing key must be provided` error message you're seeing is thrown when OpenIddict is unable to find an appropriate signing key to sign an access token.

That said, a check is made at startup time to ensure at least one signing key is manually registered if a new key cannot be dynamically generated and stored (`At least one signing key must be registered.`). Not sure why you're not seeing this exception.

The `opencsp failed with error code 2148073494` exception sounds a bit cryptic. Do you have a more complete exception trace? Also, could you share more details about your environment? (e.g are you running on .NET Desktop or on .NET Core?)

**Comment by snowping** [comment]
Thanks for your fast response. I use .NET Core (latest 1.0.0) on a Windows 2012 R2 server with IIS 8.5.9600. This is my exception trace when I try to let a key to be generated:

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: A signing key must be provided.
System.InvalidOperationException: A signing key must be provided.
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SerializeAccessTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<InvokeTokenEndpointAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

**The exception trace when I use my own certificate:**

```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: OpenCSP failed with error code 2148073494.
System.Security.Cryptography.CryptographicException: OpenCSP failed with error code 2148073494.
   at Internal.NativeCrypto.CapiHelper.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeProvHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider.get_SafeKeyHandle()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 keySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(CspParameters parameters)
   at Internal.Cryptography.Pal.CertificatePal.<>c.<GetRSAPrivateKey>b__59_0(CspParameters csp)
   at Internal.Cryptography.Pal.CertificatePal.GetPrivateKey[T](Func`2 createCsp, Func`2 createCng)
   at Internal.Cryptography.Pal.CertificatePal.GetRSAPrivateKey()
   at Internal.Cryptography.Pal.CertificateExtensionsCommon.GetPrivateKey[T](X509Certificate2 certificate, Predicate`1 matchesConstraints)
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_PrivateKey()
   at Microsoft.IdentityModel.Tokens.X509SecurityKey.get_HasPrivateKey()
   at Microsoft.IdentityModel.Tokens.AsymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityToken(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<SerializeAccessTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<InvokeTokenEndpointAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.ApplicationInsights.AspNetCore.ExceptionTrackingMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
```

**Comment by kevinchalet** [comment]
And you're not seeing any error at startup? I'll try to replicate your scenario: the app should "crash" during startup when no signing key can be generated.

Concerning the second bug, can you please try running your app on .NET Desktop to see if it changes something?

**Comment by snowping** [comment]
Nope, the app is running besides the authentication (/connect/token). I only get warnings but they seem not to be related:
warn: 

```
Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[8]
      The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
```

How can I run the app in .NET Desktop mode? Do I need to change the libraries in project.json? (sorry I am new to asp dev)

**Comment by kevinchalet** [comment]
> How can I run the app in .NET Desktop mode? Do I need to change the libraries in project.json? (sorry I am new to asp dev)

Yep, you need to target `net451` instead of `netcoreapp1.0` (under frameworks, in project.json)

**Comment by kevinchalet** [comment]
Hum, I can't reproduce the first bug on my machine. I get the expected exception at startup:

![image](https://cloud.githubusercontent.com/assets/6998306/16969832/218d330c-4e18-11e6-84d2-700fb59f337b.png)

Is there a chance you could enable logging (debug level) and share your complete logs?

**Comment by snowping** [comment]
seems not about an easy switch from .net core to .net desktop as several code parts are not working anymore... 
Using my dev machine it also works but on iis host... I am generating the logs now.. just a sec.

**Comment by kevinchalet** [comment]
> Using my dev machine it also works but on iis host...

FYI, I tested on IIS 7.5 (Windows 7), with ApplicationPoolIdentity and "load user profile" disabled.

**Comment by snowping** [comment]
here my debug log (issue with my own cert)
[stdout_7288_2016719234036.zip](https://github.com/openiddict/openiddict-core/files/372638/stdout_7288_2016719234036.zip)

**Comment by kevinchalet** [comment]
That's all you get? There's nothing before these 2 lines?

```
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[3]
      Hosting starting
dbug: Microsoft.AspNetCore.Hosting.Internal.WebHost[4]
      Hosting started
```

**Comment by snowping** [comment]
yes, hmm maybe I need to change some iis settings as well..

**Comment by kevinchalet** [comment]
If you could share a complete log in the first scenario (without any certificate), that would help.

A bunch of questions:
- How did you register your certificate in the machine store?
- Are you using a custom identity for your app pool?
- Have you correctly set the private key permissions?

**Comment by snowping** [comment]
ok, here my debug log with first scenario: 
[stdout_6352_2016719235810.zip](https://github.com/openiddict/openiddict-core/files/372650/stdout_6352_2016719235810.zip)

**Comment by snowping** [comment]
To answer your questions:
- Using the helper tool from keith: https://www.pluralsight.com/blog/software-development/selfcert-create-a-self-signed-certificate-interactively-gui-or-programmatically-in-net
  => tested with "My" and with "Root" store
- No, I use the 'ApplicationPoolIdentity'
- Which private key permission do you mean?

**Comment by kevinchalet** [comment]
Thanks for the log, it helped me find the first bug (a stupid return at the wrong place). I'll fix it in the next release.

> Which private key permission do you mean?

I mean the read permission you have to grant to the app pool identity to allow IIS to access the private key associated with your certificate: http://stackoverflow.com/a/3176253/542757

**Comment by snowping** [comment]
Good point, I was not aware of that. You are awesome! That did the trick with my own certificate. Thank you very much for your help and patience.

**Comment by kevinchalet** [comment]
Glad it worked :clap: 

Surprisingly, the error you were seeing was a bit cryptic (more than the `Keyset not found` error we usually see on .NET Desktop when there's a permission issue somewhere).

I'll ping @bartonjs tomorrow and ask him if the CoreFX team has plans to re-align the error messages between .NET Desktop and .NET Core.

**Comment by bartonjs** [comment]
@PinpointTownes My ears are burning :fire:.

Yeah, I'm not sure off the top of my head why the error is different.  2148073494 does seem to be the same Keyset does not exist error.  I think this line got messed up when it moved from inside the VM to inside managed code.  If you haven't already, it'd be good to open a bug in corefx; I'll want to spend more than a few seconds seeing what changed to figure out why.

**Comment by kevinchalet** [comment]
@bartonjs thanks for your prompt answer :smile: 

I opened a ticket to track that: https://github.com/dotnet/corefx/issues/10218. Feel free to rename it if the title doesn't illustrate the work item.

@snowping FYI, the automatic RSA key generation/persistence feature was completely removed from ASOS/OpenIddict. Registering an explicit key/certificate is now mandatory and an exception is thrown if you don't.

**Comment by snowping** [comment]
@PinpointTownes Ok, good to know. Thanks.

**Comment by rajivcodes** [comment]
So that means its required even when you running on localmachine (using IISExpress) ? Why would we want it when we are just creating the app and testing it on our local machine? Cant we bypass it and only keep it when we are in production mode?

**Comment by kevinchalet** [comment]
That's right.

If you don't want to configure a static certificate/key, you can generate an in-memory/ephemeral key by calling `AddEphemeralSigningKey`.
