### ISSUE TITLE
Error after login

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#176]
Hi,

I'm having some trouble setting up OpenIddict.

I have my ASP.NET Identity site setup with OpenIddict and i'm am trying to authenticate from a WebForms website. When I hit the WebForms website I get redirected to the Identity site where I login and get redirected to https://localid2.idsite.org/connect/authorize?request_id=1c3fede0-707b-48cb-bdd4-f7b14c056775 which shows an error? I have copied the authorize views and controller from the sample

Error log shows

```
2016-07-29 10:15:48.893 +01:00 [Information] Authorization was successful for user: "David".
2016-07-29 10:15:48.906 +01:00 [Error] An unhandled exception has occurred: Unable to resolve service for type 'OpenIddict.OpenIddictApplicationManager`1[OpenIddict.OpenIddictApplication`1[System.Guid]]' while attempting to activate 'MPS.IdentityServer.Controllers.AuthorizationController'.
System.InvalidOperationException: Unable to resolve service for type 'OpenIddict.OpenIddictApplicationManager`1[OpenIddict.OpenIddictApplication`1[System.Guid]]' while attempting to activate 'MPS.IdentityServer.Controllers.AuthorizationController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
2016-07-29 10:15:48.916 +01:00 [Debug] The request path "/Home/Error" does not match a supported file type
2016-07-29 10:15:48.917 +01:00 [Information] HttpContext.User merged via AutomaticAuthentication from authenticationScheme: "Identity.Application".
2016-07-29 10:15:48.917 +01:00 [Debug] Authentication was skipped because no bearer token was received.
2016-07-29 10:15:48.917 +01:00 [Debug] Request successfully matched the route with name '"default"' and template '"{controller=Account}/{action=Login}/{id?}"'.
2016-07-29 10:15:48.918 +01:00 [Debug] No actions matched the current request
2016-07-29 10:15:48.918 +01:00 [Debug] Request did not match any routes.
```

Statup.cs of Webforms website

```
public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions());

            app.UseOpenIdConnectAuthentication(
                new OpenIdConnectAuthenticationOptions
                {
                    Authority = "https://localid2.idsite.org",

                    ClientId = "B5FD5590-1E99-4EB1-86FE-B65416C5FF37",
                    ClientSecret = "abcedef",
                    RedirectUri = "http://localhost:3467/signin-oidc",
                    PostLogoutRedirectUri = "http://localhost:3467/",

                    ResponseType = "code",

                    Scope = "openid email"
                }
            );
        }
```

**Comment by kevinchalet** [comment]
Sharing your `ConfigureServices` method would help.

**Comment by daver77** [comment]
Here you go

```
services.AddOpenIddict<ApplicationUser, ApplicationDbContext>()

    .EnableAuthorizationEndpoint("/connect/authorize")
    .EnableLogoutEndpoint("/connect/logout")
    .EnableTokenEndpoint("/connect/token")
    .EnableUserinfoEndpoint("/connect/userinfo")
    .AllowAuthorizationCodeFlow()
    .AllowImplicitFlow();
    .AddSigningCertificate(Configuration["AppSettings:CertificateThumbprint"]);
```

The error seems to be

InvalidOperationException: Unable to resolve service for type 'OpenIddict.OpenIddictApplicationManager`1[OpenIddict.OpenIddictApplication`1[System.Guid]]' while attempting to activate 'MPS.IdentityServer.Controllers.AuthorizationController'.

**Comment by kevinchalet** [comment]
You can't use `OpenIddictApplicationManager<OpenIddictApplication<Guid>>` if you don't override the default entity key type (`string` -> `Guid`).

Instead, use `OpenIddictApplicationManager<OpenIddictApplication>`.

**Comment by daver77** [comment]
Thanks for that. I get to the authorisation page now and get redirected back to the relying party site. The site does seem to save a cookie named OpenIdConnectxxxxxx by Request.IsAuthenticated is false, do you know what i'm missing

I'm redirecting to the Identity site using this on my replying party

```
            if (!Request.IsAuthenticated)
            {
                HttpContext.Current.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties { RedirectUri = "http://localhost:3467/" },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
```

**Comment by kevinchalet** [comment]
> ResponseType = "code",

http://stackoverflow.com/questions/33661935/owin-middleware-for-openid-connect-code-flow-flow-type-authorizationcode/33662736#33662736

**Comment by daver77** [comment]
Ah, so it should be
`ResponseType = "id_token"`

This throws an error on /connect/authorize/accept/

2016-07-29 14:40:39.230 +01:00 [Debug] Executed action method "MPS.IdentityServer.Controllers.AuthorizationController.Accept (IdServer)", returned result "Microsoft.AspNetCore.Mvc.SignInResult".
2016-07-29 14:40:39.230 +01:00 [Information] Executing SignInResult with authentication scheme ("ASOS") and the following principal: "System.Security.Claims.ClaimsPrincipal".
2016-07-29 14:40:39.245 +01:00 [Debug] System.Security.Cryptography.CryptographicException occurred, checking if Entity Framework recorded this exception as resulting from a failed database operation.
2016-07-29 14:40:39.245 +01:00 [Debug] Entity Framework did not record any exceptions due to failed database operations. This means the current exception is not a failed Entity Framework database operation, or the current exception occurred from a DbContext that was not obtained from request services.
2016-07-29 14:40:39.245 +01:00 [Error] An unhandled exception has occurred while executing the request
System.Security.Cryptography.CryptographicException: Keyset does not exist

**Comment by kevinchalet** [comment]
You know you can search error codes on Google/Bing/Yahoo, right? :sweat_smile: 

https://github.com/openiddict/openiddict-core/issues/169#issuecomment-233800475

**Comment by daver77** [comment]
Indeed :) Cert not setup correctly from the look of it!

**Comment by daver77** [comment]
All working now !
Final question of the day :) Is it possible to skip the auth pages so that when logging in successfully it just goes straight back to the return uri?

**Comment by kevinchalet** [comment]
> Is it possible to skip the auth pages so that when logging in successfully it just goes straight back to the return uri?

Since you're responsible of creating the authorization controller, it's up to you to implement that.

**Comment by daver77** [comment]
Oh yeah, easy as that :)

Thanks for all your help!
