### ISSUE TITLE
Error when creating Migration script

### ISSUE THREAD

**Issue by brion-fuller** [openiddict/openiddict-core#177]
I'm currently trying to create my initial migration script using the template that is location [here](https://github.com/openiddict/openiddict-core/tree/dev/samples/Mvc.Server/Models).  When I run Add-Migration Initial, I receive the error below.

```
PM> Add-Migration Initial
No parameterless constructor was found on 'ApplicationDbContext'. Either add a parameterless constructor to 'ApplicationDbContext' or add an implementation of 'IDbContextFactory<ApplicationDbContext>' in the same assembly as 'ApplicationDbContext'.
```

**Comment by Bartmax** [comment]
Are you using ASP.NET Core? @brion-fuller

**Comment by brion-fuller** [comment]
Yes, everything runs fine when I have Identity hooked up but errors when I move applicationdbcontext and applicationuser over.

**Comment by Bartmax** [comment]
Entity Framework 6 or Entity Framework Core ? Did you try adding a parameterless constructor to ApplicationDbContext as the error suggest?

**Comment by brion-fuller** [comment]
This issue can be closed, Entity Framework was corrupted.  The error before when I added the constructor is below.

```
System.IO.FileLoadException: Could not load file or assembly 'System.Interactive.Async, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: 'System.Interactive.Async, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
    at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddQuery(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.AddEntityFramework(IServiceCollection serviceCollection)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_0.<GetOrAdd>b__1(Int64 k)
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options) 
   at Microsoft.AspNetCore.Identity.EntityFrameworkCore.IdentityDbContext`3..ctor()
    at OpenIddict.OpenIddictDbContext`7..ctor()
    at OpenIddict.OpenIddictDbContext`3..ctor()
```

**Comment by kevinchalet** [comment]
So was having a parameterless constructor mandatory to fix your issue?

I'm a bit surprised the migration stack can't handle the `DbContextOptions`, which is what we use to flow things like the connection string up to `DbContext`.

**Comment by brion-fuller** [comment]
No, I removed the parameterless constructor and uninstalled Entity Framework Core and reinstalled the package.  Everything worked fine after that.  There was no issue on OpenIdDict side.

**Comment by kevinchalet** [comment]
Alright, thanks for the heads-up.
