### ISSUE TITLE
ID0115 InvalidOperationException after upgrading to v4?

### ISSUE THREAD

**Issue by hangy** [openiddict/openiddict-core#1875]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

## Summary

After upgrading from OpenIddict server 2.0.1 to 4.7.0, users using a single third-party client aren't able to sign in, any more.

## Steps

1. User login at the relying party causes front channel/browser to open `https://openiddict.example.com/connect/authorize?response_type=code&redirect_uri=https://client.example.org/web/sso/login/redacted-auth&client_id=redacted&scope=openid email profile offline_access&state=zvfQjQ`
1. If necessary, user signs in or authorizes RP
1. OpenIddict front channel redirects the user back to the RP `https://client.example.org/web/sso/login/redacted-auth?code=redacted&state=zvfQjQ&iss=https%3A%2F%2Fopeniddict.example.com%2F`
1. RP tries back channel request to get a token with a POST to `https://openiddict.example.com/connect/token` and body `grant_type=authorization_code&code=redacted&redirect_uri=https%3A%2F%2Fclient.example.org%2Fweb%2Fsso%2Flogin%2Fredacted-auth&client_id=redacted&client_secret=redacted`
1. Exception is thrown by OpenIddict, and 400 Bad Request is returned to the RP
```
System.InvalidOperationException: Only strings, booleans, integers, arrays of strings and instances of type 'OpenIddictParameter' or 'JsonElement' can be returned as custom parameters. On .NET 6.0 and higher, instances of type 'JsonNode' (i.e 'JsonArray', 'JsonObject' and 'JsonValue') are also supported.
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandlers.ResolveHostSignInProperties.HandleAsync(ProcessSignInContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.OpenIddictServerDispatcher.DispatchAsync[TContext](TContext context)
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.SignInAsync(ClaimsPrincipal user, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.SignInAsync(HttpContext context, String scheme, ClaimsPrincipal principal, AuthenticationProperties properties)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

## Analysis

I tried to replace the default `ResolveHostSignInProperties` handler by one that prints the "bad" value. It seems to be `.authorization_code_principal`, which is a bit confusing, because that Parameter value seems to be set by OpenIddict in https://github.com/openiddict/openiddict-core/blob/23d8d9bdfe0729451464c085439c83d02018e33a/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs#L271. I attempted using a custom version of `ResolveHostSignInProperties` that simply ignores all values that are of type `ClaimsPrincipal`, but that didn't help, because the RP app now claims the user is unknown. That doesn't sound too unreasonable, given I removed all the claims. 😅

## Environment

The OpenIddict application is running .NET 6.0.15 on Windows Server 2019.

<details>
<summary>NuGet package references</summary>

```xml
  <ItemGroup>
    <PackageReference Include="App.Metrics.AspNetCore.Mvc" Version="4.3.0" />
    <PackageReference Include="App.Metrics.Formatters.Prometheus" Version="4.3.0" />
    <PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="6.0.2" />
    <PackageReference Include="IdentityModel" Version="6.1.0" />
    <PackageReference Include="MediatR" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="6.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="6.0.1" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.6.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.32.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.18.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols" Version="6.32.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.WsFederation" Version="6.32.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens.Saml" Version="6.32.1" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="4.7.0" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="4.7.0" />
    <PackageReference Include="Serilog.Extensions.Logging.File" Version="3.0.0" />
    <PackageReference Include="Sustainsys.Saml2" Version="2.9.1" />
  </ItemGroup>
```

</details>

**Comment by kevinchalet** [comment]
Hey,

Thanks for sponsoring the project, much appreciated! ❤️ 

In your token endpoint action (typically in your authorization controller), do you happen to call `return SignIn(...)` with an `AuthenticationProperties` instance that is directly taken from the `AuthenticateResult` object? E.g:

```csharp
var result = await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
return SignIn(result.Principal, result.Properties, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
```

If so, update that call to avoid flowing the properties, that should fix the error you're seeing:

```csharp
var result = await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
return SignIn(result.Principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
```

Hope it'll help.

**Comment by kevinchalet** [comment]
Doing some housecleaning but feel free to reopen if you need additional details 😃
