### ISSUE TITLE
Introspection validation failure

### ISSUE THREAD

**Issue by 2d1a0ec3** [openiddict/openiddict-core#1935]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

5.0.0

### Describe the bug

A unhadled `System.NullReferenceException` exception is thrown when introspecting a token on the resource server.

It looks that the handler `OpenIddict.Validation.OpenIddictValidationHandlers.Protection.ValidateExpirationDate` throws a `System.NullReferenceException` when it tries to access the recently introduced  (507ced1) `ClockSkew` property from `context.TokenValidationParameters`. `.TokenValidationParameters` is not initialized, becuase the handler `OpenIddict.Validation.OpenIddictValidationHandlers.Protection.ResolveTokenValidationParameters` is filtered out with `.AddFilter<RequireLocalValidation>()` and not executed when running an Introspection Validation.

### To reproduce

Just run Zirku sample from openiddict-samples (I ran `.Server` + `.Api1` + `.Client1`).

### Exceptions (if any)

```shell
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at OpenIddict.Validation.OpenIddictValidationHandlers.Protection.ValidateExpirationDate.HandleAsync(ValidateTokenContext context)
         at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
         at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
         at OpenIddict.Validation.OpenIddictValidationHandlers.ValidateAccessToken.HandleAsync(ProcessAuthenticationContext context)
         at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
         at OpenIddict.Validation.OpenIddictValidationDispatcher.DispatchAsync[TContext](TContext context)
         at OpenIddict.Validation.AspNetCore.OpenIddictValidationAspNetCoreHandler.HandleAuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by kevinchalet** [comment]
I received a similar report earlier today, so it’s definitely impacting. 
I’ll make sure it’s fixed as part of the next patch.

Thanks.

**Comment by mantas-masidlauskas** [comment]
when we can expect this fix to be released ?

**Comment by kevinchalet** [comment]
https://github.com/openiddict/openiddict-core/releases/tag/5.0.1
