### ISSUE TITLE
Exception when using self-signed certificate

### ISSUE THREAD

**Issue by jayrulez** [openiddict/openiddict-core#314]
I'm getting an error on application startup because of an exception with the signing certificate.

I am using a self signed certificate from this tool: https://s3.amazonaws.com/pluralsight-free/keith-brown/samples/SelfCert.zip

```c#
.AddSigningCertificate(
                      assembly: typeof(Startup).GetTypeInfo().Assembly,
                      resource: "Caricoin.API.Certificate.pfx",
                      password: "password here");
```

Microsoft.AspNetCore.Hosting.Internal.WebHost:Critical: Application startup exception

Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Access denied
   at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(Byte[] rawData, String password, PfxCertStoreFlags pfxCertStoreFlags)
   at Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(Byte[] rawData, String fileName, String password, X509KeyStorageFlags keyStorageFlags)
   at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, Stream stream, String password, X509KeyStorageFlags flags)
   at Microsoft.AspNetCore.Builder.OpenIdConnectServerExtensions.AddCertificate(IList`1 credentials, Assembly assembly, String resource, String password)
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.<>c__DisplayClass5_0.<AddSigningCertificate>b__0(OpenIddictOptions options)
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.UseOpenIddict(IApplicationBuilder app)
   at Caricoin.API.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in C:\Users\Robert\Desktop\Caricoin\src\Caricoin.API\Startup.cs:line 327
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Any idea why this might be happening?

**Comment by jayrulez** [comment]
After some google-foo, I ran VS as administrator and it works. Not sure why this didn't happen before windows crashed on me and I had to reset it.

**Comment by jayrulez** [comment]
Problem with windows
