### ISSUE TITLE
Error using Authorization Code sample

### ISSUE THREAD

**Issue by daver77** [openiddict/openiddict-core#318]
Hi,
I'm using the sample below to test my OpenIddict auth provider
https://github.com/openiddict/openiddict-samples/tree/master/samples/CodeFlow/ClientApp

After login, I redirect back to http://localhost:4495/signin-oidc and get an error, any ideas what can cause this?

```
AggregateException: Unhandled remote failure. (Response status code does not indicate success: 400 (Bad Request).)
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__19.MoveNext()
```

**Comment by kevinchalet** [comment]
Please share your logs.

**Comment by daver77** [comment]
Here you go

```
2017-01-05 14:16:18.325 +00:00 [Information] Executing action method "StsClientCore.Controllers.AuthenticationController.SignIn (StsClientCore)" with arguments (null) - ModelState is Valid
2017-01-05 14:16:18.332 +00:00 [Information] Executing ChallengeResult with authentication schemes (["OpenIdConnect"]).
2017-01-05 14:16:19.064 +00:00 [Information] AuthenticationScheme: "OpenIdConnect" was challenged.
2017-01-05 14:16:19.065 +00:00 [Information] Executed action "StsClientCore.Controllers.AuthenticationController.SignIn (StsClientCore)" in 741.3888ms
2017-01-05 14:16:19.065 +00:00 [Information] Request finished in 742.732ms 302 
2017-01-05 14:16:27.033 +00:00 [Information] Request starting HTTP/1.1 POST http://localhost:4495/signin-oidc application/x-www-form-urlencoded 1751
2017-01-05 14:16:27.140 +00:00 [Error] Exception occurred while processing message.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__19.MoveNext()
2017-01-05 14:16:27.144 +00:00 [Information] Error from RemoteAuthentication: "Response status code does not indicate success: 400 (Bad Request).".
2017-01-05 14:16:27.148 +00:00 [Error] An unhandled exception has occurred while executing the request
System.AggregateException: Unhandled remote failure. (Response status code does not indicate success: 400 (Bad Request).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRemoteCallbackAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRequestAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__6.MoveNext()
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<RedeemAuthorizationCodeAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.<HandleRemoteAuthenticateAsync>d__19.MoveNext()<---

2017-01-05 14:16:27.292 +00:00 [Information] Request finished in 259.1657ms 500 text/html; charset=utf-8

```

**Comment by kevinchalet** [comment]
I meant the OIDC server app logs :trollface:

**Comment by daver77** [comment]
Here you go :)
I see the error at the bottom, I don't understand it though?
The token request was rejected with the following error: "invalid_request" ; "Public clients are not allowed to send a client_secret."

```
2017-01-05 14:27:45.014 +00:00 [Information] User profile not available. Using '"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\ASP.NET\4.0.30319.0\AutoGenKeys\S-1-5-82-2165650817-1256634210-951654888-656913806-3292931200\DataProtection"' as key repository and Windows DPAPI to encrypt keys at rest.
2017-01-05 14:27:45.294 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/.well-known/openid-configuration  
2017-01-05 14:27:45.671 +00:00 [Information] Request finished in 390.8554ms 200 application/json;charset=UTF-8
2017-01-05 14:27:45.928 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/.well-known/jwks  
2017-01-05 14:27:45.951 +00:00 [Information] Request finished in 22.8286ms 200 application/json;charset=UTF-8
2017-01-05 14:27:46.271 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/connect/authorize?client_id=StsClientCore&redirect_uri=http%3A%2F%2Flocalhost%3A4495%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl&state=CfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI  
2017-01-05 14:27:47.143 +00:00 [Warning] The LINQ expression 'SingleOrDefault()' could not be translated and will be evaluated locally. To configure this warning use the DbContextOptionsBuilder.ConfigureWarnings API (event id 'RelationalEventId.QueryClientEvaluationWarning'). ConfigureWarnings can be used when overriding the DbContext.OnConfiguring method or using AddDbContext on the application service provider.
2017-01-05 14:27:47.292 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__identifier_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [application].[Id], [application].[ClientId], [application].[ClientSecret], [application].[DisplayName], [application].[LogoutRedirectUri], [application].[RedirectUri], [application].[Type]
FROM [OpenIddictApplications] AS [application]
WHERE [application].[ClientId] = @__identifier_0
2017-01-05 14:27:47.635 +00:00 [Information] Authorization failed for user: null.
2017-01-05 14:27:47.636 +00:00 [Warning] Authorization failed for the request at filter '"Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter"'.
2017-01-05 14:27:47.641 +00:00 [Information] Executing ChallengeResult with authentication schemes ([]).
2017-01-05 14:27:47.657 +00:00 [Information] AuthenticationScheme: "Identity.Application" was challenged.
2017-01-05 14:27:47.658 +00:00 [Information] Request finished in 1386.6312ms 302 
2017-01-05 14:27:47.663 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/Account/Login?ReturnUrl=%2Fconnect%2Fauthorize%3Fclient_id%3DStsClientCore%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A4495%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520roles%26response_mode%3Dform_post%26nonce%3D636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl%26state%3DCfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI  
2017-01-05 14:27:50.679 +00:00 [Information] Executing action method "MPS.IdentityServer.Controllers.AccountController.Login (IdServer)" with arguments (["/connect/authorize?client_id=StsClientCore&redirect_uri=http%3A%2F%2Flocalhost%3A4495%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl&state=CfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI", ""]) - ModelState is Valid
2017-01-05 14:27:54.892 +00:00 [Information] Executing ViewResult, running view at path "/Views/Account/Login.cshtml".
2017-01-05 14:27:56.329 +00:00 [Information] Executed action "MPS.IdentityServer.Controllers.AccountController.Login (IdServer)" in 8631.9412ms
2017-01-05 14:27:56.331 +00:00 [Information] Request finished in 8667.945ms 200 text/html; charset=utf-8
2017-01-05 14:27:56.544 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/favicon.ico  
2017-01-05 14:27:56.764 +00:00 [Information] Request finished in 194.0944ms 404 
2017-01-05 14:28:03.006 +00:00 [Information] Request starting HTTP/1.1 POST http://localid.medicalprotection.org/?returnurl=%2Fconnect%2Fauthorize%3Fclient_id%3DStsClientCore%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A4495%252Fsignin-oidc%26response_type%3Dcode%26scope%3Dopenid%2520profile%2520email%2520roles%26response_mode%3Dform_post%26nonce%3D636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl%26state%3DCfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI application/x-www-form-urlencoded 221
2017-01-05 14:28:03.285 +00:00 [Information] Executing action method "MPS.IdentityServer.Controllers.AccountController.Login (IdServer)" with arguments (["MPS.IdentityServer.Models.AccountViewModels.LoginViewModel", "/connect/authorize?client_id=StsClientCore&redirect_uri=http%3A%2F%2Flocalhost%3A4495%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl&state=CfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI"]) - ModelState is Valid
2017-01-05 14:28:03.302 +00:00 [Information] Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE') SELECT 1 ELSE SELECT 0
2017-01-05 14:28:03.362 +00:00 [Information] Executed DbCommand (2ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[CrmMembershipId], [u].[Email], [u].[EmailConfirmed], [u].[IditContactId], [u].[JoinedOn], [u].[LastLoggedIn], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MembershipNumber], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SchemeCode], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
2017-01-05 14:28:03.559 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__userId_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT [role].[Name]
FROM [AspNetUserRoles] AS [userRole]
INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
WHERE [userRole].[UserId] = @__userId_0
2017-01-05 14:28:03.583 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__user_Id_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
FROM [AspNetUserClaims] AS [uc]
WHERE [uc].[UserId] = @__user_Id_0
2017-01-05 14:28:03.608 +00:00 [Information] AuthenticationScheme: "Identity.Application" signed in.
2017-01-05 14:28:03.619 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[CrmMembershipId], [u].[Email], [u].[EmailConfirmed], [u].[IditContactId], [u].[JoinedOn], [u].[LastLoggedIn], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MembershipNumber], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SchemeCode], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
2017-01-05 14:28:03.637 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__normalizedUserName_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[CrmMembershipId], [u].[Email], [u].[EmailConfirmed], [u].[IditContactId], [u].[JoinedOn], [u].[LastLoggedIn], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MembershipNumber], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SchemeCode], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedUserName] = @__normalizedUserName_0
2017-01-05 14:28:03.654 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__normalizedEmail_0='?' (Size = 256)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[CrmMembershipId], [u].[Email], [u].[EmailConfirmed], [u].[IditContactId], [u].[JoinedOn], [u].[LastLoggedIn], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MembershipNumber], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SchemeCode], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[NormalizedEmail] = @__normalizedEmail_0
2017-01-05 14:28:03.831 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@p20='?' (Size = 450), @p0='?', @p1='?' (Size = 4000), @p21='?' (Size = 4000), @p2='?', @p3='?' (Size = 256), @p4='?', @p5='?' (Size = 4000), @p6='?', @p7='?', @p8='?', @p9='?', @p10='?' (Size = 6), @p11='?' (Size = 256), @p12='?' (Size = 256), @p13='?' (Size = 4000), @p14='?' (Size = 4000), @p15='?', @p16='?' (Size = 3), @p17='?' (Size = 4000), @p18='?', @p19='?' (Size = 256), @p22='?' (Size = 450), @p23='?', @p24='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
UPDATE [AspNetUsers] SET [AccessFailedCount] = @p0, [ConcurrencyStamp] = @p1, [CrmMembershipId] = @p2, [Email] = @p3, [EmailConfirmed] = @p4, [IditContactId] = @p5, [JoinedOn] = @p6, [LastLoggedIn] = @p7, [LockoutEnabled] = @p8, [LockoutEnd] = @p9, [MembershipNumber] = @p10, [NormalizedEmail] = @p11, [NormalizedUserName] = @p12, [PasswordHash] = @p13, [PhoneNumber] = @p14, [PhoneNumberConfirmed] = @p15, [SchemeCode] = @p16, [SecurityStamp] = @p17, [TwoFactorEnabled] = @p18, [UserName] = @p19
WHERE [Id] = @p20 AND [ConcurrencyStamp] = @p21;
SELECT @@ROWCOUNT;
INSERT INTO [LoginHistory] ([ApplicationUserId], [OccurredOn], [Type])
VALUES (@p22, @p23, @p24);
SELECT [LoginHistoryId]
FROM [LoginHistory]
WHERE @@ROWCOUNT = 1 AND [LoginHistoryId] = scope_identity();
2017-01-05 14:28:03.856 +00:00 [Information] User logged in.
2017-01-05 14:28:03.859 +00:00 [Information] Executing RedirectResult, redirecting to "/connect/authorize?client_id=StsClientCore&redirect_uri=http%3A%2F%2Flocalhost%3A4495%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl&state=CfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI".
2017-01-05 14:28:03.860 +00:00 [Information] Executed action "MPS.IdentityServer.Controllers.AccountController.Login (IdServer)" in 846.5048ms
2017-01-05 14:28:03.860 +00:00 [Information] Request finished in 854.2373ms 302 
2017-01-05 14:28:03.865 +00:00 [Information] Request starting HTTP/1.1 GET http://localid.medicalprotection.org/connect/authorize?client_id=StsClientCore&redirect_uri=http%3A%2F%2Flocalhost%3A4495%2Fsignin-oidc&response_type=code&scope=openid%20profile%20email%20roles&response_mode=form_post&nonce=636192232659856646.MjZiZjE2N2MtNWM0YS00MTI5LWJmOGMtMDc5ODNlNThjMDJkYzE1OWU0N2ItOTRiMC00NTU5LWExZjAtMGM0MjBlMjMwMzhl&state=CfDJ8FAU6BSWckROk0SFaqKtP3OxgpMNtRIXnpvS3IWucOaUxPTcomh9f4jvKy5B06QY-Geq3aj9kM9EaRgUEPwH82hFDCSCx3ApBByLn1VN30Wfv33WgDH3E_tTbpgqhgD2bhM5jVk5Te5Md48vKzPaJEm4aYEmWEdnSKgeKgeinh19Nlud2L5Qvlsgfug27wYuE5Vg-zUIvnUSZyf8ZYqwAoS1P0jVPfj4XZej4TKfCy3k3f-zO3Sw21eLTHwkxzXN3TDfW_fAMyynlX3O7E4mPXJXa2HMZVylqhqw3gqjczWl0yUrcRA6ZHoqlsXKRdsKgmQMWXPb8erORaoZq4Q-alI  
2017-01-05 14:28:03.876 +00:00 [Information] HttpContext.User merged via AutomaticAuthentication from authenticationScheme: "Identity.Application".
2017-01-05 14:28:03.878 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__identifier_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [application].[Id], [application].[ClientId], [application].[ClientSecret], [application].[DisplayName], [application].[LogoutRedirectUri], [application].[RedirectUri], [application].[Type]
FROM [OpenIddictApplications] AS [application]
WHERE [application].[ClientId] = @__identifier_0
2017-01-05 14:28:03.878 +00:00 [Information] Authorization was successful for user: "David123".
2017-01-05 14:28:03.882 +00:00 [Information] Executing action method "MPS.IdentityServer.Controllers.AuthorizationController.Authorize (IdServer)" with arguments (["AspNet.Security.OpenIdConnect.Primitives.OpenIdConnectRequest"]) - ModelState is Valid
2017-01-05 14:28:03.885 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__identifier_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [application].[Id], [application].[ClientId], [application].[ClientSecret], [application].[DisplayName], [application].[LogoutRedirectUri], [application].[RedirectUri], [application].[Type]
FROM [OpenIddictApplications] AS [application]
WHERE [application].[ClientId] = @__identifier_0
2017-01-05 14:28:03.894 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__id_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(1) [u].[Id], [u].[AccessFailedCount], [u].[ConcurrencyStamp], [u].[CrmMembershipId], [u].[Email], [u].[EmailConfirmed], [u].[IditContactId], [u].[JoinedOn], [u].[LastLoggedIn], [u].[LockoutEnabled], [u].[LockoutEnd], [u].[MembershipNumber], [u].[NormalizedEmail], [u].[NormalizedUserName], [u].[PasswordHash], [u].[PhoneNumber], [u].[PhoneNumberConfirmed], [u].[SchemeCode], [u].[SecurityStamp], [u].[TwoFactorEnabled], [u].[UserName]
FROM [AspNetUsers] AS [u]
WHERE [u].[Id] = @__id_0
2017-01-05 14:28:03.900 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__userId_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT [role].[Name]
FROM [AspNetUserRoles] AS [userRole]
INNER JOIN [AspNetRoles] AS [role] ON [userRole].[RoleId] = [role].[Id]
WHERE [userRole].[UserId] = @__userId_0
2017-01-05 14:28:03.902 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__user_Id_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT [uc].[Id], [uc].[ClaimType], [uc].[ClaimValue], [uc].[UserId]
FROM [AspNetUserClaims] AS [uc]
WHERE [uc].[UserId] = @__user_Id_0
2017-01-05 14:28:03.909 +00:00 [Information] Executing SignInResult with authentication scheme ("ASOS") and the following principal: "System.Security.Claims.ClaimsPrincipal".
2017-01-05 14:28:03.948 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@p0='?' (Size = 450), @p1='?' (Size = 450), @p2='?' (Size = 450), @p3='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [OpenIddictTokens] ([Id], [ApplicationId], [AuthorizationId], [Type])
VALUES (@p0, @p1, @p2, @p3);
2017-01-05 14:28:03.963 +00:00 [Information] AuthenticationScheme: "ASOS" signed in.
2017-01-05 14:28:03.963 +00:00 [Information] Executed action "MPS.IdentityServer.Controllers.AuthorizationController.Authorize (IdServer)" in 85.4503ms
2017-01-05 14:28:03.964 +00:00 [Information] Request finished in 98.574ms 200 text/html;charset=UTF-8
2017-01-05 14:28:04.075 +00:00 [Information] Request starting HTTP/1.1 POST http://localid.medicalprotection.org/connect/token application/x-www-form-urlencoded 1529
2017-01-05 14:28:04.102 +00:00 [Information] Executed DbCommand (0ms) [Parameters=[@__identifier_0='?' (Size = 450)], CommandType='Text', CommandTimeout='30']
SELECT TOP(2) [application].[Id], [application].[ClientId], [application].[ClientSecret], [application].[DisplayName], [application].[LogoutRedirectUri], [application].[RedirectUri], [application].[Type]
FROM [OpenIddictApplications] AS [application]
WHERE [application].[ClientId] = @__identifier_0
2017-01-05 14:28:04.104 +00:00 [Error] The token request was rejected because the public application '"StsClientCore"' was not allowed to send a client secret.
2017-01-05 14:28:04.105 +00:00 [Error] The token request was rejected with the following error: "invalid_request" ; "Public clients are not allowed to send a client_secret."
2017-01-05 14:28:04.108 +00:00 [Information] Request finished in 33.5829ms 400 application/json;charset=UTF-8
```

**Comment by kevinchalet** [comment]
> I see the error at the bottom, I don't understand it though?

The message is ultra clear: your app is a public app, so it doesn't make any sense to send a client_secret, which is something specific to confidential apps. OpenIddict detects you're doing something wrong and rejects the request.

**Comment by daver77** [comment]
I see, I misunderstood public vs confidential, it should be confidential.

**Comment by daver77** [comment]
I have set the application to confidential in the database and now the .NET Core sample works fine.
