### ISSUE TITLE
How to use OpenIddictTokenManager?

### ISSUE THREAD

**Issue by altair256** [openiddict/openiddict-core#380]
Hello! I try revoke the refresh_token and for this i try to use OpenIddictManager.

```
        ...
        private readonly OpenIddictTokenManager<OpenIddictToken> _tokenManager;

        public AuthorizationController(            
            SignInManager<Person> signInManager,
            UserManager<Person> userManager,
            OpenIddictTokenManager<OpenIddictToken> tokenManager,
            IOptions<IdentityOptions> identityOptions) : base(null, signInManager, userManager)
        {
            _tokenManager = tokenManager;
            _identityOptions = identityOptions;            
        }
        ...
```

But when I try log in in my application an error occurs:

```
...
System.InvalidOperationException: Unable to resolve service for type 'OpenIddict.Core.OpenIddictTokenManager`1[OpenIddict.Models.OpenIddictToken]' while attempting to activate 'Altair.Web.Controllers.AuthorizationController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
...
```

You can tell me how to correct initialize OpenIddictManager and then use it? Or give me an example of use.

Thanky for help!

**Comment by kevinchalet** [comment]
> You can tell me how to correct initialize OpenIddictManager and then use it?

Nope... not if you don't share your OpenIddict configuration :smile:

**Comment by altair256** [comment]
> Nope... not if you don't share your OpenIddict configuration 😄

Sorry... Here is my OpenIddict configuration.

```
...
 services.AddOpenIddict<int>()
                .AddEntityFrameworkCoreStores<AltairDbContext>()
                .AddMvcBinders()
                .UseJsonWebTokens()
                .EnableTokenEndpoint(Configuration["Authentication:OpenIddict:TokenEndPoint"])
                .EnableLogoutEndpoint(Configuration["Authentication:OpenIddict:LogoutEndPoint"])                      .EnableAuthorizationEndpoint(Configuration["Authentication:OpenIddict:AuthorizationEndPoint"])
                .EnableUserinfoEndpoint(Configuration["Authentication:OpenIddict:UserInfoEndPoint"])
                .AllowPasswordFlow()
                .AllowAuthorizationCodeFlow()
                .AllowImplicitFlow()
                .AllowRefreshTokenFlow()               
                .RequireClientIdentification()
                .EnableRequestCaching()
                .SetAccessTokenLifetime(TimeSpan.FromSeconds(30))                
                .AddEphemeralSigningKey();
        }
...
```

**Comment by kevinchalet** [comment]
Looks like you're using a custom key type, so you must fix your code accordingly:

```
OpenIddictTokenManager<OpenIddictToken>
```

->

```
OpenIddictTokenManager<OpenIddictToken<int>>
```

**Comment by altair256** [comment]
Thank you for help! Now this work fine!
