### ISSUE TITLE
Unable to cast OpenIddictToken to OpenIddictAuthorization

### ISSUE THREAD

**Issue by bradmarder** [openiddict/openiddict-core#586]
I'm not sure what is going on here. This is using the latest packages with `guid` keys.

```
System.InvalidCastException: Unable to cast object of type 'System.Func`3[CustomDbContext,System.Guid,System.Threading.Tasks.Task`1[OpenIddict.Models.OpenIddictToken`1[System.Guid]]]' to type 'System.Func`3[CustomDbContext,System.Guid,System.Threading.Tasks.Task`1[OpenIddict.Models.OpenIddictAuthorization`1[System.Guid]]]'.
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at OpenIddict.EntityFrameworkCore.OpenIddictAuthorizationStore`5.FindByIdAsync(String identifier, CancellationToken cancellationToken)
   at OpenIddict.Core.OpenIddictAuthorizationManager`1.FindByIdAsync(String identifier, CancellationToken cancellationToken)
   at OpenIddict.OpenIddictProvider`4.<TryRevokeAuthorizationAsync>d__29.MoveNext()
   at OpenIddict.OpenIddictProvider`4.<HandleTokenRequest>d__25.MoveNext()
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<InvokeTokenEndpointAsync>d__20.MoveNext()
   at AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerHandler.<HandleRequestAsync>d__3.MoveNext()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__8.MoveNext()
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.<Invoke>d__3.MoveNext()
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.<ProcessRequestsAsync>d__185`1.MoveNext()
```

**Comment by kevinchalet** [comment]
Thanks tor reporting this bug. 

Looks like a case of caching key collision. I’ll fix it tonight.
