### ISSUE TITLE
OpenIddict with SqlLite (in memory) for integration tests

### ISSUE THREAD

**Issue by tjpeel** [openiddict/openiddict-core#684]
I'm trying to configure Sql Lite (in memory) for integration tests and I can't seem to get it working. This is my config:

```
services.AddDbContext<DbContext>(
    options =>
    {
        // options.UseInMemoryDatabase(nameof(DbContext));
        options.UseSqlite("DataSource=:memory:");
        options.UseOpenIddict();
    });
```

And for OpenIddict:

```
services
    .AddOpenIddict()
    .AddCore(
        options =>
        {
            options
                .UseEntityFrameworkCore()
                .UseDbContext<DbContext>();
        })
    .AddServer(
        options =>
        {
            options.UseMvc();
            options.DisableHttpsRequirement();
            options.UseJsonWebTokens();
        });
```

I have a seed process that is run on startup, where I ensure the database is created:

```
internal static class Seed
{
    internal static async Task InitializeAsync(IServiceProvider services, bool ensureDatabaseCreated = false)
    {
        // Create a new service scope to ensure the database context is correctly disposed when this methods returns.
        using (var scope = services.GetRequiredService<IServiceScopeFactory>().CreateScope())
        {
            if (ensureDatabaseCreated)
            {
                var context = scope.ServiceProvider.GetService<DbContext>();
                context.Database.EnsureCreated();
            }

            await CreateApplicationsAsync();
            
            // ... snipped for brevity
```

As a result, I can see the schema being created in logs when running integration tests:

```
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: None
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (9ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA foreign_keys=ON;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT COUNT(*) FROM "sqlite_master" WHERE "type" = 'table' AND "rootpage" IS NOT NULL;
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "OpenIddictApplications" (
          "ClientId" TEXT NOT NULL,
          "ClientSecret" TEXT NULL,
          "ConcurrencyToken" TEXT NULL,
          "ConsentType" TEXT NULL,
          "DisplayName" TEXT NULL,
          "Id" TEXT NOT NULL CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY,
          "Permissions" TEXT NULL,
          "PostLogoutRedirectUris" TEXT NULL,
          "Properties" TEXT NULL,
          "RedirectUris" TEXT NULL,
          "Type" TEXT NOT NULL
      );

// ... snipped for brevity
```

Yet when my app executes, I get the following error:

```
Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'no such table: OpenIddictApplications'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at OpenIddict.Core.OpenIddictApplicationCache`1.<>c__DisplayClass6_0.<<FindByClientIdAsync>g__ExecuteAsync|0>d.MoveNext()
```

The only difference I can see is that the configuration differs to the EFCore in memory mode where `options.UseInMemoryDatabase(nameof(DbContext));` is using the DbContext that OpenIddict then uses `options.UseEntityFrameworkCore().UseDbContext<DbContext>();`. 

Yet the SqlLite line `options.UseSqlite("DataSource=:memory:");` doesn't use the DbContext. So I presume the tables are being created yet OpenIddict isn't using the same database?

I was only exploring SqlLite as I was experiencing some odd behaviour when running integration tests for my token exchange process using an EFCore in memory database. Tests would run in isolation OK but when run together one would fail, despite each test creating its own client via the `WebApplicationFactory<Startup>` method.

Any thoughts greatly appreciated, thanks

**Comment by kevinchalet** [comment]
That's because Sqlite's in-memory databases are cleared when the connection is closed. To work around that, you can create a single connection and share it between all your `DbContext` instances: https://docs.microsoft.com/en-us/ef/core/miscellaneous/testing/sqlite#writing-tests

> I was only exploring SqlLite as I was experiencing some odd behaviour when running integration tests for my token exchange process using an EFCore in memory database. Tests would run in isolation OK but when run together one would fail, despite each test creating its own client via the WebApplicationFactory<Startup> method.

I'd love to hear more about that. Any chance you could share more info (like the exception type/message/stack trace)?

**Comment by tjpeel** [comment]
Thanks for the quick reply, much appreciated. Noted re: SqlLite, it's not really what I wanted to use anyway. Regarding my other issue, these are my tests:

```
[Test]
public async Task Exchange_WhenPost_AndInvalidSecretThenReturnsBadRequest()
{
    // Arrange
    using (var factory = new CustomWebApplicationFactory())
    {
        var client = factory.CreateClient(
            new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });
        var content = new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                ["grant_type"] = "client_credentials",
                ["client_id"] = "company1-client1",
                ["client_secret"] = "secret"
            });

        // Act
        var response = await client.PostAsync("/company1/connect/token", content);
        var oidcResponse = JsonConvert.DeserializeObject<OpenIdConnectResponse>(
            await response.Content.ReadAsStringAsync());

        // Assert
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.Unauthorized));
        Assert.That(oidcResponse.Error, Is.EqualTo("invalid_client"));
        Assert.That(oidcResponse.ErrorDescription, Is.EqualTo("The specified client credentials are invalid."));
    }
}

[Test]
public async Task Exchange_WhenPost_AndValidCredentialsThenReturnsOk()
{
    // Arrange
    using (var factory = new CustomWebApplicationFactory())
    {
        var client = factory.CreateClient(
            new WebApplicationFactoryClientOptions
            {
                AllowAutoRedirect = false
            });
        var content = new FormUrlEncodedContent(
            new Dictionary<string, string>
            {
                ["grant_type"] = "client_credentials",
                ["client_id"] = "company1-client1",
                ["client_secret"] =
                    "vsLQrEEYQsnsrhVPcZmcyvCeQxt9zXzr9HKj7AybNhDNLcRnhvzs59j7wmHdar5rhC2NpzRnE6FK9DtfQcWhW2wNXMDkqy2XnZyL"
            });

        // Act
        var response = await client.PostAsync("/company1/connect/token", content);
        var oidcResponse = JsonConvert.DeserializeObject<OpenIdConnectResponse>(
            await response.Content.ReadAsStringAsync());

        // Assert
        Assert.That(response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
        Assert.That(oidcResponse.AccessToken, Is.Not.Null);
        Assert.That(oidcResponse.AccessToken.Length, Is.GreaterThan(0));
    }
}
```

My Startup configuration is as stated in my original post, but using EFCore in memory instead of SqlLite.

Run together, the first test above passes with:

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
warn: OpenIddict.Core.OpenIddictApplicationManager[0]
      Client authentication failed for company1-client1.
fail: OpenIddict.Server.Internal.OpenIddictServerProvider[0]
      The token request was rejected because the confidential or hybrid application 'company1-client1' didn't specify valid client credentials.
fail: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was rejected with the following error: invalid_client ; The specified client credentials are invalid.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "error": "invalid_client",
        "error_description": "The specified client credentials are invalid."
      }.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 217.7892ms 401 application/json;charset=UTF-8
```

Yet the second one fails with:

```
  Expected: OK
  But was:  Unauthorized

info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
fail: OpenIddict.Server.Internal.OpenIddictServerProvider[0]
      The token request was rejected because the client application was not found: 'company1-client1'.
fail: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was rejected with the following error: invalid_client ; The specified 'client_id' parameter is invalid.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "error": "invalid_client",
        "error_description": "The specified 'client_id' parameter is invalid."
      }.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.5099ms 401 application/json;charset=UTF-8
```

Run in isolation, the first test passes with the same debug logs. And the second test passes with the following:

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=DbContext 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully validated.
dbug: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The default token request handling was skipped from user code.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Exchange", controller = "Authorisation"}. Executing action Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication) with arguments ({
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication), returned result Microsoft.AspNetCore.Mvc.SignInResult in 10.0947ms.
info: Microsoft.AspNetCore.Mvc.SignInResult[1]
      Executing SignInResult with authentication scheme (ASOS) and the following principal: System.Security.Claims.ClaimsPrincipal.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "token_type": "Bearer",
        "access_token": "[removed for security reasons]",
        "expires_in": 3600
      }.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication) in 217.096ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 702.7586ms 200 application/json;charset=UTF-8
```

So comparing the second test when it's run in conjunction with the first (the left) and when it's run on its own (the right), the `OpenIddict.Server.Internal.OpenIddictServerProvider` fails with `The token request was rejected because the client application was not found: 'company1-client1'.`

![image](https://user-images.githubusercontent.com/1770224/47575987-4b095200-d93b-11e8-84ac-d66a6d9421cc.png)

This is my token exchange controller action:

```
[HttpPost("~/connect/token"), Produces("application/json")]
public async Task<IActionResult> Exchange(OpenIdConnectRequest request)
{
    Debug.Assert(request.IsTokenRequest(),
        "The OpenIddict binder for ASP.NET Core MVC is not registered. " +
        "Make sure services.AddOpenIddict().AddMvcBinders() is correctly called.");

    if (request.IsClientCredentialsGrantType())
    {
        // Note: the client credentials are automatically validated by OpenIddict:
        // if client_id or client_secret are invalid, this action won't be invoked.

        var application = await _applicationManager.FindByClientIdAsync(request.ClientId, HttpContext.RequestAborted);
        if (application == null)
        {
            return BadRequest(new OpenIdConnectResponse
            {
                Error = OpenIdConnectConstants.Errors.InvalidClient,
                ErrorDescription = "The client application was not found in the database."
            });
        }

        _currentCompany = HttpContext.Features.Get<ICompanyTenantFeature>().CurrentCompany;

        // TODO Implement company specific applications other than by name convention

        if (!application.ClientId.StartsWith(_currentCompany.Domain))
        {
            return BadRequest(new OpenIdConnectResponse
            {
                Error = OpenIdConnectConstants.Errors.InvalidClient,
                ErrorDescription = "The client application is invalid."
            });
        }

        // Create a new authentication ticket.
        var ticket = CreateTicket(_currentCompany, application);

        return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
    }

    return BadRequest(new OpenIdConnectResponse
    {
        Error = OpenIdConnectConstants.Errors.UnsupportedGrantType,
        ErrorDescription = "The specified grant type is not supported."
    });
}
```

It's as if the same database is being used and the clear down from the first test run is removing the client application that the second test is trying to use. Yet, as I'm creating a new server each time, I would have expected there to be separate in memory databases that could not be affected by things like other tests.

Another point to note is that I do have some multi tenant configuration running:

```
public class OpenIddictServerOptionsConfiguration : IConfigureNamedOptions<OpenIddictServerOptions>
{
    private readonly IDataProtectionProvider _dataProtectionProvider;
    private readonly CompanyTenantService _companyTenantService;

    public OpenIddictServerOptionsConfiguration(
        IDataProtectionProvider dataProtectionProvider,
        CompanyTenantService companyTenantService)
    {
        _dataProtectionProvider = dataProtectionProvider;
        _companyTenantService = companyTenantService;
    }

    public void Configure(string name, OpenIddictServerOptions options) => Configure(options);

    public void Configure(OpenIddictServerOptions options)
    {
        var company = _companyTenantService.GetCurrentCompany().GetAwaiter().GetResult();

        if (company == null) return;
        
        // TODO Investigate what impact this actually having seen as we use JWT

        // Create a tenant-specific data protection provider to ensure authorization codes,
        // access tokens and refresh tokens can't be read/decrypted by the other tenants.
        options.DataProtectionProvider = _dataProtectionProvider.CreateProtector(company.Domain);

        if (!string.IsNullOrWhiteSpace(company.SigningKey))
        {
            options.SigningCredentials.AddKey(new SymmetricSecurityKey(Encoding.UTF8.GetBytes(company.SigningKey)));
        }

        if (company.GrantTypes.Implicit)
        {
            options.TokenEndpointPath = "/connect/token";
            options.AuthorizationEndpointPath = "/connect/authorise";
            options.LogoutEndpointPath = "/connect/logout";
            options.UserinfoEndpointPath = "/connect/userinfo";
            options.IntrospectionEndpointPath = "/connect/introspect";

            options.GrantTypes.Add("implicit");

            // Throws exception if not added, will need to be a proper key for prod etc
            options.SigningCredentials.AddEphemeralKey();
        }

        if (company.GrantTypes.ClientCredentials)
        {
            options.TokenEndpointPath = "/connect/token";

            options.GrantTypes.Add("client_credentials");
        }
    }
}
```

The `_companyTenantService` just has a single company in memory. And both tests are targeting the same company - `company1` 

Thanks in advance if anything springs to mind.

**Comment by kevinchalet** [comment]
I'm tempted to think that using `options.UseInMemoryDatabase(nameof(DbContext));` causes EF to share the same underlying in-memory store for all your tests, which may result in the weird things you're describing. You should try with a test-specific name like `options.UseInMemoryDatabase("Exchange_WhenPost_AndValidCredentialsThenReturnsOk");` or something random, e.g using `options.UseInMemoryDatabase(Guid.NewGuid().ToString());`

**Comment by tjpeel** [comment]
Funny you should say that, I did actually try it and the same failure happened. But what I did see was that multiple databases were being used in the same request. You can see it with the Guid being different. I'll do it now and post back the detail.....

**Comment by tjpeel** [comment]
This is the second test output now (note the different Guids for in memory store name):

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=a0a913c9-0972-4781-a07e-fa0e443477db 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=21c57c47-e872-4dea-83b5-da9c9549037d 
fail: OpenIddict.Server.Internal.OpenIddictServerProvider[0]
      The token request was rejected because the client application was not found: 'company1-client1'.
fail: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was rejected with the following error: invalid_client ; The specified 'client_id' parameter is invalid.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "error": "invalid_client",
        "error_description": "The specified 'client_id' parameter is invalid."
      }.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 219.6922ms 401 application/json;charset=UTF-8
```

Could it be the use of `WebApplicationFactory<Startup>` perhaps?

I'll try refactoring now so the test name can be chained through a test specific startup.

Does feel like the in memory store is being shared though like you say.

**Comment by kevinchalet** [comment]
Are you using some sort of startup initialization like what we do in the samples, that create a scope to create the applications?

If so, then having 2 different contexts - that are scoped - is expected. Using a fixed test-specific store name could be a nice solution to work around that.

**Comment by tjpeel** [comment]
Yes, I have this:

```
internal static class Seed
{
    internal static async Task InitializeAsync(IServiceProvider services, bool ensureDatabaseCreated = false)
    {
        // Create a new service scope to ensure the database context is correctly disposed when this methods returns.
        using (var scope = services.GetRequiredService<IServiceScopeFactory>().CreateScope())
        {
            await CreateApplicationsAsync();

            async Task CreateApplicationsAsync()
            {
                var manager = scope.ServiceProvider.GetRequiredService<OpenIddictApplicationManager<OpenIddictApplication>>();

                if (await manager.FindByClientIdAsync("company1-client1") == null)
                {
                    var descriptor = new OpenIddictApplicationDescriptor
                    {
                        ClientId = "company1-client1",
                        ClientSecret = "vsLQrEEYQsnsrhVPcZmcyvCeQxt9zXzr9HKj7AybNhDNLcRnhvzs59j7wmHdar5rhC2NpzRnE6FK9DtfQcWhW2wNXMDkqy2XnZyL",
                        DisplayName = "Company 1 - Client 1",
                        Permissions =
                        {
                            OpenIddictConstants.Permissions.Endpoints.Token,
                            OpenIddictConstants.Permissions.GrantTypes.ClientCredentials
                        }
                    };

                    var app = await manager.CreateAsync(descriptor);

                    await manager.UpdateAsync(app);
                }
            }
        }
    }
}
```

I'm just trying to work out how best I can inject the test name into all the startup behaviour. Feels like some progress though, which is good, thanks again for assistance!

**Comment by tjpeel** [comment]
Hmmm, same issue. Second test erroring (when run in parallel):

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=Exchange_WhenPost_AndValidCredentialsThenReturnsOk 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=Exchange_WhenPost_AndValidCredentialsThenReturnsOk 
fail: OpenIddict.Server.Internal.OpenIddictServerProvider[0]
      The token request was rejected because the client application was not found: 'company1-client1'.
fail: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was rejected with the following error: invalid_client ; The specified 'client_id' parameter is invalid.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "error": "invalid_client",
        "error_description": "The specified 'client_id' parameter is invalid."
      }.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2.7376ms 401 application/json;charset=UTF-8
```

Then succeeding when run in isolation:

```
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\TimPeel\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=Exchange_WhenPost_AndValidCredentialsThenReturnsOk 
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.EntityFrameworkCore.Update[30100]
      Saved 1 entities to in-memory store.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/2.0 POST http://localhost/company1/connect/token application/x-www-form-urlencoded 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 2.1.3-rtm-32065 initialized 'DbContext' using provider 'Microsoft.EntityFrameworkCore.InMemory' with options: StoreName=Exchange_WhenPost_AndValidCredentialsThenReturnsOk 
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully validated.
dbug: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The default token request handling was skipped from user code.
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Exchange", controller = "Authorisation"}. Executing action Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication) with arguments ({
        "grant_type": "client_credentials",
        "client_id": "company1-client1",
        "client_secret": "[removed for security reasons]"
      }) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication), returned result Microsoft.AspNetCore.Mvc.SignInResult in 9.5313ms.
info: Microsoft.AspNetCore.Mvc.SignInResult[1]
      Executing SignInResult with authentication scheme (ASOS) and the following principal: System.Security.Claims.ClaimsPrincipal.
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token response was successfully returned: {
        "token_type": "Bearer",
        "access_token": "[removed for security reasons]",
        "expires_in": 3600
      }.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Company.Authentication.Controllers.AuthorisationController.Exchange (Company.Authentication) in 229.4399ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 717.8155ms 200 application/json;charset=UTF-8
```

So it must be something else in my setup that is leading to the problem.

**Comment by kevinchalet** [comment]
Have you tried to share the `WebApplicationFactory` instead of creating a new instance every time? Assuming you never remove the applications from the in-memory database, it should work fine in parallel.

**Comment by tjpeel** [comment]
Yes, good suggestion, and this worked when I tried it. However, ideally I'd like to keep things fully isolated and know what my tests setup is actually correct when they run, regardless of running in parallel or within context of a fixture.

I may switch approach and look at mocking the data store instead (similar to how you do things in your tests). I can then remove the need for any in memory EFCore instance. Longer term I'll be using MongoDb anyway.

Ideally I'd just like a in memory application store for the time being. Don't know if something like that would be of use as a basic storage mechanism just to get example implementations up and running?

Thanks again

**Comment by kevinchalet** [comment]
> However, ideally I'd like to keep things fully isolated and know what my tests setup is actually correct when they run, regardless of running in parallel or within context of a fixture.

Well, in integration tests, running things in parallel against a shared DB is generally a good thing as it allows detecting threading issues that can't be caught easily.

> Don't know if something like that would be of use as a basic storage mechanism just to get example implementations up and running?

I've considered it but I'm not sure it's worth it now that we have a very good in-memory store in EF Core.

When you have a moment, consider uploading your tests project (that uses EF Core in-memory) somewhere so I can take a look. It's not clear to me why things fail when you have a WAF per test.

**Comment by tjpeel** [comment]
Thanks, and I will do

**Comment by georgeonofrei** [comment]
@PinpointTownes I have a simplistic implementation of in memory stores for dev purposes. If it's useful, let me know where I can put it.

**Comment by tjpeel** [comment]
@georgeonofrei push to a repo perhaps?

**Comment by jonathanantoine** [comment]
please share it with us @georgeonofrei  :)

**Comment by kevinchalet** [comment]
FYI, I posted more details about the in-memory database issue here: https://github.com/openiddict/openiddict-core/issues/698#issuecomment-447594003 (TL;DR: it's a bug in EF Core that impacts compiled queries).
