### ISSUE TITLE
dependency problem in caching

### ISSUE THREAD

**Issue by ahmed-abouelkhaire** [openiddict/openiddict-core#70]
using rc2 nightly build 20116
openiddict core project failed to build because of this line in OpenIddictExtensions 

```
builder.Services.AddCaching();
```

what  lead me to discover this error is when i tried to update my project database using dotnet ef
it gave me this error

```
dotnet : System.TypeLoadException: Could not load type 'Microsoft.Extensions.DependencyInjection.MemoryCacheServicesExtensions' from assembly 'Microsoft.Extensions.Caching.Memory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
At line:1 char:1
+ dotnet ef database update
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.TypeLoad...9793829ddae60'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.AddOpenIddictCore[TApplication](IdentityBuilder builder, Action`1 configuration)
   at Microsoft.AspNetCore.Builder.OpenIddictExtensions.AddOpenIddict(IdentityBuilder builder)

   at WebPortal.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Ahmed-PC\Development\RoseDevProject\RoseDev\src\WebPortal\Startup.cs:line 52

Could not load type 'Microsoft.Extensions.DependencyInjection.MemoryCacheServicesExtensions' from assembly 'Microsoft.Extensions.Caching.Memory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

please can you update the project with the correct dependency 
thanks a lot

**Comment by kevinchalet** [comment]
Thanks for reporting this bug :clap: 

Fixed: https://github.com/openiddict/openiddict-core/commit/576d42bc35705740bd761c1a30fc3ba9e7144162.

FY, it was caused by a breaking change added yesterday in the caching block: https://github.com/aspnet/Caching/commit/a6c044c1590b16c98df1cc6d01eca1140a86ee99.
