### ISSUE TITLE
[3.0]: Unable to track an entity of type 'BTCPayOpenIdAuthorization' because primary key property 'Id' is null

### ISSUE THREAD

**Issue by NicolasDorier** [openiddict/openiddict-core#834]
Tests of openiddict on .net 3.0 are failing, but work well on 2.1. (we use openiddict3.0 in both case) 3.0.0-alpha1.19515.63

Entity Framework breaking change of not initializing primary keys anymore.

```
Unit.net 00:02:35.66]         }.
Test run in progress...[xUnit.net 00:02:35.66]         10/21/2019 09:45:29 +00:00 :OpenIddict.Server.OpenIddictServerProvider:   The authorization request was successfully validated.
Test run in progress...[xUnit.net 00:02:35.66]         10/21/2019 09:45:29 +00:00 :Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware:   An unhandled exception has occurred while executing the request.
Test run in progress...[xUnit.net 00:02:35.66]         System.InvalidOperationException: Unable to track an entity of type 'BTCPayOpenIdAuthorization' because primary key property 'Id' is null.
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
Test run in progress...[xUnit.net 00:02:35.66]            at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
Test run in progress...[xUnit.net 00:02:35.66]            at OpenIddict.EntityFrameworkCore.OpenIddictAuthorizationStore`5.CreateAsync(TAuthorization authorization, CancellationToken cancellationToken) in /_/src/OpenIddict.EntityFrameworkCore/Stores/OpenIddictAuthorizationStore.cs:line 168
Test run in progress...[xUnit.net 00:02:35.66]            at OpenIddict.Core.OpenIddictAuthorizationManager`1.CreateAsync(TAuthorization authorization, CancellationToken cancellationToken) in /_/src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs:line 131
Test run in progress...[xUnit.net 00:02:35.66]            at OpenIddict.Core.OpenIddictAuthorizationManager`1.CreateAsync(OpenIddictAuthorizationDescriptor descriptor, CancellationToken cancellationToken) in /_/src/OpenIddict.Core/Managers/OpenIddictAuthorizationManager.cs:line 164
Test run in progress...[xUnit.net 00:02:35.66]            at BTCPayServer.Controllers.AuthorizationController.Authorize(String consent, Boolean createAuthorization) in /source/BTCPayServer/Controllers/AuthorizationController.cs:line 128
```

**Comment by kevinchalet** [comment]
Looks like a breaking change in EF Core 3.0, that no longer assigns a default value for `string` and `byte[]` primary keys client-side: https://docs.microsoft.com/fr-fr/ef/core/what-is-new/ef-core-3.0/breaking-changes#string-and-byte-array-keys-are-not-client-generated-by-default

Our default "non-generic" entities are not impacted because we always manually generate the key for them (e.g: https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.EntityFrameworkCore.Models/OpenIddictAuthorization.cs#L21)

I'll consider using `.ValueGeneratedOnAdd()` in the EF Core model configurations, but I'll have to test that extensively (with EF Core 2.x, with EF Core 3.x, with int/long/Guid keys types, etc.) so it will likely take some time.

In the meantime, you can add the same call to your EF Core configs' or manually attach a key in the constructors of your custom entities.

**Comment by NicolasDorier** [comment]
@PinpointTownes I gave up on .net core 3.0. There is too many breaking thing (not only openiddict), will try again in .net core 3.1.
