### ISSUE TITLE
[3.0] OpenIddict 3 + SignalR 3 Authentication

### ISSUE THREAD

**Issue by dlimkin** [openiddict/openiddict-core#873]
Hello, 
I maked authentication on OpenIddict 3 (NetCore3.1), but I can't get it to work with SignalR 3

**Startup ConfigureServices**
```services.AddOpenIddict()
                .AddCore(options =>
                {
                    options.UseEntityFrameworkCore()
                        .UseDbContext<StaffDbContext>();
                })
                .AddServer(options =>
                {
                    options
                        .SetTokenEndpointUris(Configuration["OpenIddict:Endpoints:Token"])
                        .SetUserinfoEndpointUris(Configuration["OpenIddict:Endpoints:Userinfo"]);

                    options
                        .AllowPasswordFlow()
                        .AllowRefreshTokenFlow();

                    options.RegisterClaims(Configuration.GetSection("OpenIddict:Claims").Get<string[]>());
                    options.RegisterScopes(Configuration.GetSection("OpenIddict:Scopes").Get<string[]>());

                    options.AddDevelopmentEncryptionCertificate()
                        .AddDevelopmentSigningCertificate();

                    options.UseAspNetCore()
                        .EnableStatusCodePagesIntegration()
                        .EnableAuthorizationEndpointPassthrough()
                        .EnableTokenEndpointPassthrough()
                        .EnableUserinfoEndpointPassthrough()
                        .DisableTransportSecurityRequirement();

                     options.AddDevelopmentEncryptionCertificate()
                        .AddDevelopmentSigningCertificate();
                })
                .AddValidation(o =>
                {
                    o.UseLocalServer();
                    o.UseReferenceAccessTokens();
                    o.UseAspNetCore();
                });
```

**Startup Configure**
```
 if (!Environment.IsDevelopment())
            {
                app.UseHsts();
                app.UseHttpsRedirection();
            }
            else
            {
                app.UseDeveloperExceptionPage();
                InitializeAsync(app.ApplicationServices).GetAwaiter().GetResult();
            }

            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
            });

           
            app.UseRouting();
            app.UseCors("Clients");

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapHub<StaffHub>("/hub/staff", options =>
                {
                    options.Transports = HttpTransportType.WebSockets;
                });
                
                endpoints.MapControllerRoute("api_template", "api/{controller}/{action}");
            });
```
**Hub**

```
    [Authorize(AuthenticationSchemes = OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)]
    public class StaffHub : Microsoft.AspNetCore.SignalR.Hub
    {
        public Task JoinGroup(string groupName)
        {
            Console.WriteLine("JoinGroup " + groupName + ": "  + Context.ConnectionId);
            return Groups.AddToGroupAsync(Context.ConnectionId, groupName);
        }

        public Task LeaveGroup(string groupName)
        {
            Console.WriteLine("LeaveGroup " + groupName + ": "  + Context.ConnectionId);
            return Groups.RemoveFromGroupAsync(Context.ConnectionId, groupName);
        }
    }
```
I get **System.InvalidOperationException**
```
System.InvalidOperationException: No identity cannot be extracted from this request.
   at OpenIddict.Server.OpenIddictServerHandlers.ValidateAuthenticationDemand.HandleAsync(ProcessAuthenticationContext context) in /_/src/OpenIddict.Server/OpenIddictServerHandlers.cs:line 153
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.HandleAuthenticateAsync() in /_/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs:line 127
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authorization.Policy.PolicyEvaluator.AuthenticateAsync(AuthorizationPolicy policy, HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
Please, help. How to fix this?

**Comment by kevinchalet** [comment]
It's the expected behavior: the OpenIddict server ASP.NET Core handler is not meant to be used to validate tokens for endpoints it doesn't own.

Replace `OpenIddictServerAspNetCoreDefaults.AuthenticationScheme` by `OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme`.

**Comment by kevinchalet** [comment]
I'll update the exception message to mention that, since it's a quite common user error (not new in 3.0, BTW).

**Comment by dlimkin** [comment]
> Replace `OpenIddictServerAspNetCoreDefaults.AuthenticationScheme` by `OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme`.

Thanks a lot, now everything works

**Comment by kevinchalet** [comment]
Good to hear!

**Comment by kevinchalet** [comment]
The exception message was improved as part of https://github.com/openiddict/openiddict-core/pull/876.

**Comment by stantoxt** [comment]
I am using default openidcore config,but I have 401 problem.
