### ISSUE TITLE
TypeLoadException for TokenValidationResult in ValidateIdentityModelToken

### ISSUE THREAD

**Issue by knoxi** [openiddict/openiddict-core#928]
We updated the package `System.IdentityModel.Tokens.Jwt` from V5.6.0 to V 6.5.0 referenced in our solution. The package was released last week.

Now we get an exception while authenticate.

```
System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.JsonWebTokens.TokenValidationResult' from assembly 'Microsoft.IdentityModel.JsonWebTokens, Version=6.5.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at OpenIddict.Server.OpenIddictServerHandlers.ValidateIdentityModelToken.HandleAsync(ProcessAuthenticationContext context)
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.OpenIddictServerHandlers.Exchange.ValidateToken.HandleAsync(ValidateTokenRequestContext context) in /_/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs:line 1373
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.OpenIddictServerHandlers.Exchange.ValidateTokenRequest.HandleAsync(ProcessRequestContext context) in /_/src/OpenIddict.Server/OpenIddictServerHandlers.Exchange.cs:line 212
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 54
   at OpenIddict.Server.OpenIddictServerProvider.DispatchAsync[TContext](TContext context) in /_/src/OpenIddict.Server/OpenIddictServerProvider.cs:line 52
   at OpenIddict.Server.AspNetCore.OpenIddictServerAspNetCoreHandler.HandleRequestAsync() in /_/src/OpenIddict.Server.AspNetCore/OpenIddictServerAspNetCoreHandler.cs:line 107
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

The only workaround we found is to roll-back the update of the package in the solution.

**Comment by kevinchalet** [comment]
@brentschmaltz @mafurman was this breaking change expected? Can we safely move to 6.5.0 without breaking ASP.NET Core 2.1 or 3.0 (or more precisely, the OIDC and JWT handlers)?

**Comment by brentschmaltz** [comment]
@knoxi @kevinchalet this is the one breaking change that will affect users. We made a mistake a put TokenValidationResult in the M.IM.JsonWebTokens namespace, instead of M.IM.Tokens. We need this type to be in M.IM.Tokens as we develop our Async model, this is a key part of that model with a signature:

`Task<TokenValidationResult> ValidateAsync(...)`

We debated keeping M.IM.JsonWebTokens.TokenValidationResult and deriving from a new type  M.IM.Tokens.TokenValidationResult, but that led to some funky docs and coding.

However, we could proceed down that path if the community needs us to fix this.

If you want us to consider this, please open an issue in our [repo](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) .

asp.net Core DOES NOT use this type.

The conversation with asp.net has started about this and other issues.
Such as they depend on JwtSecurityToken, etc...

**Comment by kevinchalet** [comment]
Thanks for taking the time to reply.

> If you want us to consider this, please open an issue in our repo.

Unlike previous versions, OpenIddict 3.0 supports ASP.NET Core 2.x, 3.x and OWIN/Katana 4.x, so if we can safely migrate to Wilson 6.5 without breaking ASP.NET Core 2.1 or OWIN/Katana, it should be fine. Are you sure there are no other breaking change that may affect 2.1 or OWIN apps?

> We need this type to be in M.IM.Tokens as we develop our Async model, this is a key part of that model with a signature:

Since validation will be sync in most cases, you'll probably want to use `ValueTask` instead of `Task` to avoid allocations 😃

**Comment by brentschmaltz** [comment]
@kevinchalet good idea about ValueTask, we will look into that.

Our thinking is the async pattern is normally a Sign or Decrypt operation as private keys are needed and KeyVault OR some similar off-box call is needed.

**Comment by kevinchalet** [comment]
> Our thinking is the async pattern is normally a Sign or Decrypt operation as private keys are needed and KeyVault OR some similar off-box call is needed.

Makes total sense. I've used `RSAKeyVaultProvider` a few times, but it ends up doing blocking calls due the fact the base `RSA` class doesn't expose async methods that Wilson could use (https://kevinchalet.com/2017/08/15/using-azure-key-vault-with-asos-and-openiddict/).

Back to the initial topic, are you 100% positive upgrading to Wilson 6.5 won't cause any other breaking change for existing ASP.NET 4.x/OWIN apps?

**Comment by brentschmaltz** [comment]
@kevinchalet

> Back to the initial topic, are you 100% positive upgrading to Wilson 6.5 won't cause any other breaking change for existing ASP.NET 4.x/OWIN apps?

Full transparency: we have focused on asp.net core.
I would be surprised if there were issues.

**Comment by kevinchalet** [comment]
Hahaha, thanks for your honesty, I appreciate 😄 

I'll probably give it a try later to ensure there's no regression.
