### ISSUE TITLE
Getting error when successful login.

### ISSUE THREAD

**Issue by mfarkan** [openiddict/openiddict-core#981]
Hi , I'm new at this project but I'm trying to learn. I've facing one issue with succesfuly login returning error ;

```
System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Failed to parse token response body as JSON. Status Code: 400. Content-Type: 
 ---> System.ArgumentNullException: IDX10000: The parameter 'json' cannot be a 'null' or an empty object. (Parameter 'json')
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectMessage..ctor(String json)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

```
info: OpenIddict.Server.Internal.OpenIddictServerHandler[0]
      The token request was successfully extracted from the HTTP request: {
        "client_id": "webApp",
        "client_secret": "[removed for security reasons]",
        "code": "[removed for security reasons]",
        "grant_type": "authorization_code",
        "redirect_uri": "http://localhost:55467/signin-oidc",
        "code_verifier": "Eq0rIg47OYh5Fv_hnSk46kRMCWHuhwsoS-zrywXVv14"
      }.
```
This is my web app startup ;

```
services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
            }).AddCookie(CookieAuthenticationDefaults.AuthenticationScheme)
            .AddOpenIdConnect(OpenIdConnectDefaults.AuthenticationScheme, config =>
            {
                config.ClientId = "webApp";
                config.ClientSecret = "123456";
                config.Authority = "http://localhost:53703";

                config.ResponseType = OpenIdConnectResponseType.Code;
                config.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;

                config.SignedOutCallbackPath = "/Home/Index";
                config.SaveTokens = true;
                config.RequireHttpsMetadata = false;
                config.GetClaimsFromUserInfoEndpoint = true;

                config.Scope.Add("email");
                config.Scope.Add("roles");
                config.SecurityTokenValidator = new JwtSecurityTokenHandler
                {
                    // Disable the built-in JWT claims mapping feature.
                    InboundClaimTypeMap = new Dictionary<string, string>()
                };

                config.TokenValidationParameters.NameClaimType = "name";
                config.TokenValidationParameters.RoleClaimType = "role";
            });

```
And this is the error page; 

![image](https://user-images.githubusercontent.com/20838613/84791191-f8dae000-affa-11ea-85ac-6d9e556bd859.png)

In my opinion i forgot something but i can't figure it out.

**Comment by kevinchalet** [comment]
Hey.

The exception indicates that an empty 400 response is returned when trying to communicate with the token endpoint. Are there any other message in the logs? Do you have a token action to handle token requests? Can you please share it?

Thanks.

**Comment by mfarkan** [comment]
Thank you for your reply. Yes , I've token method. Here is the method ;

```
[HttpPost("~/connect/token"), Produces("application/json")]
        public async Task<IActionResult> Exchange()
        {
            var request = HttpContext.GetOpenIdConnectRequest();
            if (request.IsClientCredentialsGrantType())
            {
                var application = await _applicationManager.FindByClientIdAsync(request.ClientId, HttpContext.RequestAborted);
                if (application == null)
                {
                    throw new InvalidOperationException("The application details cannot be found in the database.");
                }

                var identity = new ClaimsIdentity(
                    OpenIddictServerDefaults.AuthenticationScheme,
                    OpenIdConnectConstants.Claims.Name,
                    OpenIdConnectConstants.Claims.Role);

                identity.AddClaim(OpenIdConnectConstants.Claims.Name, application.DisplayName,
                    OpenIdConnectConstants.Destinations.AccessToken);

                identity.AddClaim(OpenIdConnectConstants.Claims.ClientId, application.ClientId,
                    OpenIddictConstants.Destinations.AccessToken);

                var ticket = new AuthenticationTicket(
                new ClaimsPrincipal(identity),
                new AuthenticationProperties(),
                OpenIddictServerDefaults.AuthenticationScheme);

                var scopes = request.GetScopes().ToImmutableArray();
                ticket.SetResources(await _scopeManager.ListResourcesAsync(scopes));

                return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
            }
            else if (request.IsAuthorizationCodeGrantType() || request.IsRefreshTokenGrantType())
            {
                var info = await HttpContext.AuthenticateAsync(OpenIddictServerDefaults.AuthenticationScheme);

                var user = await _userManager.GetUserAsync(info.Principal);

                if (user == null)
                {
                    return BadRequest(new OpenIdConnectResponse()
                    {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                        ErrorDescription = "The authorization code is no longer valid."
                    });
                }
                if (!await _signInManager.CanSignInAsync(user))
                {
                    return BadRequest(new OpenIdConnectResponse()
                    {
                        Error = OpenIdConnectConstants.Errors.InvalidGrant,
                        ErrorDescription = "The user is no longer allowed to sign in."
                    });
                }

                var ticket = await this.CreateTicketAsync(user, request, new AuthenticationProperties());
                return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
            }
            else if (request.IsPasswordGrantType())
            {
                var user = await _userManager.FindByNameAsync(request.Username);
                if (user == null)
                {
                    var properties = new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIdConnectConstants.Properties.Error] = OpenIdConnectConstants.Errors.InvalidGrant,
                        [OpenIdConnectConstants.Properties.ErrorDescription] = "The username/password couple is invalid."
                    });

                    return Forbid(properties, OpenIddictServerDefaults.AuthenticationScheme);
                }

                var result = await _signInManager.CheckPasswordSignInAsync(user, request.Password, true);
                if (!result.Succeeded)
                {
                    var properties = new AuthenticationProperties(new Dictionary<string, string>
                    {
                        [OpenIdConnectConstants.Properties.Error] = OpenIdConnectConstants.Errors.InvalidGrant,
                        [OpenIdConnectConstants.Properties.ErrorDescription] = "The username/password couple is invalid."
                    });

                    return Forbid(properties, OpenIddictServerDefaults.AuthenticationScheme);
                }
                var ticket = await CreateTicketAsync(user, request, new AuthenticationProperties());
                return SignIn(ticket.Principal, ticket.Properties, ticket.AuthenticationScheme);
            }
            throw new NotImplementedException("The specified grant type is not implemented.");
        }

```

```
private async Task<AuthenticationTicket> CreateTicketAsync(ApplicationUser user, OpenIdConnectRequest request, AuthenticationProperties properties)
        {
            var principal = await _signInManager.CreateUserPrincipalAsync(user);
            var ticket = new AuthenticationTicket(principal, properties, OpenIddictServerDefaults.AuthenticationScheme);

            var scopes = request.GetScopes().ToImmutableArray();
            ticket.SetScopes(request.GetScopes());
            ticket.SetResources(await _scopeManager.ListResourcesAsync(scopes));

            foreach (var claim in ticket.Principal.Claims)
            {
                if (claim.Type == "AspNet.Identity.SecurityStamp")
                {
                    continue;
                }
                var destinations = new List<string>();

                if (claim.Type == OpenIdConnectConstants.Claims.Email ||
                    claim.Type == OpenIdConnectConstants.Claims.Name ||
                    claim.Type == OpenIdConnectConstants.Claims.Role)
                {
                    destinations.Add(OpenIdConnectConstants.Destinations.AccessToken);
                }

                if ((claim.Type == OpenIdConnectConstants.Claims.Email && ticket.HasScope(OpenIdConnectConstants.Scopes.Email)) ||
                    (claim.Type == OpenIdConnectConstants.Claims.Name && ticket.HasScope(OpenIdConnectConstants.Scopes.Profile)) ||
                    (claim.Type == OpenIdConnectConstants.Claims.Role && ticket.HasScope(OpenIddictConstants.Scopes.Roles)))
                {
                    if (!destinations.Contains(OpenIdConnectConstants.Destinations.AccessToken))
                    {
                        destinations.Add(OpenIdConnectConstants.Destinations.AccessToken);
                    }
                    if (!destinations.Contains(OpenIdConnectConstants.Destinations.AccessToken))
                    {
                        destinations.Add(OpenIdConnectConstants.Destinations.IdentityToken);
                    }
                }
                claim.SetDestinations(destinations);
            }

            return ticket;

        }

```
This is the error on webApplication ;

```
fail: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler[17]
      Exception occurred while processing message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Failed to parse token response body as JSON. Status Code: 400. Content-Type: 
 ---> System.ArgumentNullException: IDX10000: The parameter 'json' cannot be a 'null' or an empty object. (Parameter 'json')
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectMessage..ctor(String json)
```

**Comment by kevinchalet** [comment]
> This is the error on webApplication ;

I meant the authorization server logs. It's not clear to me what's causing the 400 response.
Are you sure your authorization controller is not decorated with `[ValidateAntiforgeryToken]` and that your app doesn't use the `AutoValidateAntiforgeryToken` filter?

**Comment by mfarkan** [comment]
well , you're rock dude. Thanks so much. I forgot the autovalidate attribute on startup.

**Comment by kevinchalet** [comment]
![](https://media.giphy.com/media/V53jWRdPWwO0U/giphy.gif)

My pleasure :smile:
